### ISSUE TITLE
Can't check for updates

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse.2#100]
### Skin section

Other

### Current Behavior

![20241013_172253](https://github.com/user-attachments/assets/b3f2db64-bd47-4654-9353-d1bcc83ec6bc)

Hey jurial I've noticed the ability to check for updates has disappeared? Is there any other way we can do it, this is a screen shot from fuse where it was in the menu by default 

### Expected Behavior

Can manually check for updates in addon browser 

### Steps To Reproduce

Open addon browser check for updates

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
For reference to anyone else looking. Clicking any of the left categories will check for updates.
