### ISSUE TITLE
Tmdb helper not showing premiere or final indicators on fuse 2 

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.arctic.fuse.2#108]
### Skin section

Widgets

### Current Behavior

On fuse 2 the premier or final indicators not showing only when you pull calander but trakt tv shows watchlist or next episode are now missing. 
![IMG_9696](https://github.com/user-attachments/assets/c6b9f804-67f4-4ad3-b927-3975e44ab666)

### Expected Behavior

To show up

### Steps To Reproduce

Set up widgets by tmdb helper widget tv shows watchlist- recently added. 

### Screenshots and Additional Info

Should look like this

![IMG_9696](https://github.com/user-attachments/assets/d5e7a55d-b737-433e-a3be-91cb33409720)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Nothing has changed here. They display fine for me. Tmdbhelper only shows these for calendar or next up lists.

**Comment by devNaresh** [comment]
I am facing same issue. Premiere/Finale is not showing for your next episodes widget in my TV, however it's working in my PC. Also checked tmdb helper and af2 version and it's same. Don't know whats the reason.

**Comment by jurialmunkey** [comment]
Change sorting for next in tmdbhelper settings to anything other than recentlyadded.
Last week or today will have the labels.

**Comment by devNaresh** [comment]
Yes, change of sorting order to today worked, earlier it was recentlywatched.
