### ISSUE TITLE
Customise dialog background 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#116]
### Skin section

Widgets

### Current Behavior

No matter how many times I set it to slate, it always reverts back to Adaptive.

### Expected Behavior

Stay on selected

### Steps To Reproduce

Appearance
Customise dialog -
Slate
Reboot 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah I see the issue.

If you reset your highlight colours after changing the background, it should save it then (reset as choose the colour for highlight again -- just needs something to retrigger rebuilding the gradient textures).

**Comment by adamosborne83** [comment]
> Ah I see the issue.
> 
> If you reset your highlight colours after changing the background, it should save it then (reset as choose the colour for highlight again -- just needs something to retrigger rebuilding the gradient textures).

Thanks Mr:-)
