### ISSUE TITLE
🐛 Custom Menus don't work with custom submenus

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#125]
### Skin section

Widgets

### Current Behavior

When ou create a custom submenu then set the action to custom menu and add menu items... Clicking the custom submenu will do nothing.

### Expected Behavior

The menu items should open in a dialog

### Steps To Reproduce

Create a custom submenu 
Set the action to custom menu
Add items
Go back to main homepage
Click on custom submenu

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is not going to be possible. I just didn't consider this scenario and forgot to disable it to prevent it being added.

**Comment by Rinicko100** [comment]
> This is not going to be possible. I just didn't consider this scenario and forgot to disable it to prevent it being added. 

Ohh I see... No problem.  Had my fingers crossed, but I kind of assumed this might be the case.
