### ISSUE TITLE
:bug: Pressing 'Back' button closes Kodi rather than opening Options Menu

### ISSUE THREAD

**Issue by ksefton92** [jurialmunkey/skin.arctic.fuse.2#126]
### Skin section

Widgets

### Current Behavior

When on one of the Category/Home pages, pressing the 'Back' button on Apple TV, it closes the Kodi app. 

### Expected Behavior

Pressing 'Back' should (used to) open the Options Menu where you could access Settings, Quick Links etc. 

### Steps To Reproduce

Go to one of Home Pages/Categories 
Click 'Back' 
See video

### Screenshots and Additional Info

To confirm, this functionality was in place a couple of days ago. Unable to see a setting that will turn this on. 

https://github.com/user-attachments/assets/ddd9282a-c05e-4b6e-8617-183b7cb03c3f

I tried using a different hub to see if this was the issue, and now have no way of getting into Settings at all (will have to wipe Kodi Data and start again)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Ade-AV** [comment]
I have the same issue

Do you have Kodi setup to Allow remote control via the web interface? Perhaps you can reach settings from there

https://kodi.wiki/view/Web_interface

**Comment by ksefton92** [comment]
Sadly did not have remote control via web set up - I've since reinstalled Kodi and managed to add the Options Menu as a custom sub menu to one of the Categories. It's not clean and doesn't look great, but will do until I can figure out how to get the Back button to function properly again.

**Comment by jurialmunkey** [comment]
This is not the skins fault. This is a problem with your keymap.

The skin now uses the "true" kodi home screen when replacing the window with a hub.

This means that your back key is not actually mapped to the "back" action on home but is instead mapped to "quit". You need to change your keymap so that it does the back command.

**Comment by Ade-AV** [comment]
This is the way it comes for Apple TV and changing it is not so straightforward

**Comment by jurialmunkey** [comment]
> This is the way it comes for Apple TV and changing it is not so straightforward

There's nothing the skin can do about this.

The only triggers that skins have are onback, oninfo, onclick or onleft/right/down/up

These correspond to the actions
Action(Back)
Action(Info)
Action(Select)
Action(Left) etc.

IF your remote keymap does not issue `Action(Back)` when pressing the back key on your remote, then Kodi will not trigger the onback action defined in the skin for that button/list.

If you remote keymap issues Quit() instead on Home, then that's what Kodi is going to do. It has nothing to do with the skin.

According to the default keymap, long press of menu (i.e. button id 8) on the ATV remote on Home brings up the shutdownmenu (i.e. the options menu)
https://github.com/xbmc/xbmc/blob/410c628c828ba9941479391cd1f80452da3ac574/system/keymaps/customcontroller.AppleRemote.xml#L95

**Comment by ksefton92** [comment]
> This is not the skins fault. This is a problem with your keymap.

HI @jurialmunkey  thank you for the detailed reply on this! I've had a look at the keymap in 21.1 and posted below. Apologies but not too clued up on what the values would need changing to, to enable the either short or long press of the back button to bring up the Options Menu?

**Comment by ksefton92** [comment]
<keymap>
  <global>
    <customcontroller name="AppleRemote">
            <button id="1">Up</button>
            <button id="2">Down</button>
            <button id="3">Left</button>
            <button id="4">Right</button>
            <button id="5">Select</button>
            <button id="6">Back</button>
            <button id="7">Fullscreen</button>
            <button id="8">ContextMenu</button>

      
            <button id="9">Left</button>
            <button id="10">Right</button>

      
            <button id="12">PlayPause</button>

      
            <button id="13">PageUp</button>
            <button id="14">PageDown</button>
            <button id="15">Pause</button>
            <button id="16">Play</button>
            <button id="17">Stop</button>
            <button id="18">FastForward</button>
            <button id="19">Rewind</button>
            <button id="20">SkipNext</button>
            <button id="21">SkipPrevious</button>

      
            <button id="70">Play</button>
            <button id="71">Pause</button>
            <button id="72">Stop</button>
            <button id="73">SkipPrevious</button>
            <button id="74">SkipNext</button>
            <button id="75">Rewind</button>
            <button id="76">FastForward</button>
            <button id="77">OSD</button>
            <button id="78">ShowVideoMenu</button>

      
            <button id="80">Left</button>
            <button id="81">Right</button>
            <button id="82">Up</button>
            <button id="83">Down</button>

            <button id="85">Left</button>
            <button id="86">Right</button>
            <button id="87">Up</button>
            <button id="88">Down</button>

    </customcontroller>
  </global>
  <Home>
    <customcontroller name="AppleRemote">
      <button id="6">ActivateWindow(FavouritesBrowser)</button>
      <button id="8">ActivateWindow(shutdownmenu)</button>
    </customcontroller>

**Comment by jurialmunkey** [comment]
I'm not familiar enough with the AppleTV to give you advice really, but you can find details about customising keymaps on the Wiki: https://kodi.wiki/view/Keymap

The other default keymap that it could be is the Siri remote one
https://github.com/xbmc/xbmc/blob/master/system/keymaps/customcontroller.SiriRemote.xml

However, I can't see anything giving a command to minimise or quit, so there's the possibility that it is some type of hardcoded behaviour in the AppleTV or Kodi. Or possibly you've already got some other custom keymap.

**Comment by ksefton92** [comment]
Thanks @jurialmunkey as always! I made an attempt at changing the below, but sadly no joy. For now, I've just changed one of the Category actions to open the Options Menu - will keep playing around and update here if I make any progress. 

```
<Home>
    <customcontroller name="SiriRemote">
      <button id="6">ContextMenu</button>
    </customcontroller>
  </Home>
```

**Comment by jurialmunkey** [comment]
@ksefton92 - I made a change about 30mins ago which will allow for the search/options skin setting to also work for hub windows (either just the one you set to home, or for all).

So once I push the next update to 2.0.15, that might be another way around this problem -- won't solve the back button of course, but will let you move right over to where the clock is to access an options menu button so that you don't need to dedicate a full category to it.

**Comment by ksefton92** [comment]
Aah amazing, that would be a more than adequate solution! Thanks so much @jurialmunkey 🥇

**Comment by ksefton92** [comment]
> So once I push the next update to 2.0.15, that might be another way around this problem

Just to confirm, 2.0.16 update works a treat! Nice touch being able to get to Options Menu where the clock is, as well as having search back in the top left (similar to AH2). Thanks @jurialmunkey !
