### ISSUE TITLE
Widget refresh possible issue

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse.2#129]
### Skin section

Widgets

### Current Behavior

Hey jurial I've noticed past couple of days at the end of episode playback more often than not the widget will not refresh to display the next episode of something I'm watching, this could likely be a trakt issue within itself but i thought it may also be worth bringing it to your attention as I'm not entirely sure. Many thanks for all of your work. 

### Expected Behavior

After episode playback when when returning to widget homescreen the widget refreshes and displays the next episode. 

### Steps To Reproduce

Come out of playback to return to home screen 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Nothing to do with the skin. Skins don't control when widgets refresh.

Kodi refreshes *all* widget containers on playback start and end. 

Whether or not these update with different items at that time depends on the plugin (or the library) in use providing different items.
