### ISSUE TITLE
Details seek bar 

### ISSUE THREAD

**Issue by Peter3344** [jurialmunkey/skin.arctic.fuse.2#13]
### Skin section

Widgets

### Current Behavior

Enable detailed seek bar no details plot or clearlogo

### Expected Behavior

Work fine on AF

### Steps To Reproduce

1

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
You can see plot by pressing the info button (either on your remote when OSD is closed to bring up a quick view, OR the button the OSD controls to bring up the full info dialog). This has been simplified from AF1.

The clearlogo will be fixed soon.
