### ISSUE TITLE
:bug: Short Description

### ISSUE THREAD

**Issue by ninopina** [jurialmunkey/skin.arctic.fuse.2#142]
### Skin section

Other

### Current Behavior

Si has visto toda la temporada si lo muestra. Pero si estás viendo un episodio de una temporada que no esté acabada no lo marca 
![20241018_121141](https://github.com/user-attachments/assets/9143bd74-d511-44cf-a915-14a88bc202c6)

### Expected Behavior

Cuando acabe un episodio se ponga el click verde de que ya está visto
![20241018_121141](https://github.com/user-attachments/assets/4fd71996-21ba-46a0-be96-f90d76ba6989)

### Steps To Reproduce

Pe

### Screenshots and Additional Info

![20241018_121141](https://github.com/user-attachments/assets/a76d6411-24f6-4f49-a6df-f596eee6277e)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
English please.

**Comment by ninopina** [comment]
If you complete a season, it does mark the views, but if you watch a single episode, it does not mark it until you have seen the entire season. I hope that with an update it will be solved, thank you very much
