### ISSUE TITLE
:bug: Random sort error

### ISSUE THREAD

**Issue by BenVB1** [jurialmunkey/skin.arctic.fuse.2#143]
### Skin section

Widgets

### Current Behavior

Selecting 'Random' sort, on both widgets & spotlight, results in the next page indicator also randomly appearing anywhere within the listing.

### Expected Behavior

In the case of widgets, would expect to see the next page indicator at the end of the listing.

In the case of spotlights, skipping the next page indicator would look a lot nicer.

### Steps To Reproduce

Select 'Random' as sort method in the widgets & spotlight creation screens. See results in display screens.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Nothing to do with the skin. Whatever plugin you're using is not correctly setting the special sort property for the next page item to ensure that it ignores sorting and appears at the end.
