### ISSUE TITLE
Serious Bug! Cannot believe been missed. 

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#148]
### Skin section

Widgets

### Current Behavior

Holiday Themes
Winter Frost NOT WORKING

### Expected Behavior

In the winter evenings to see snow flakes across my screen

### Steps To Reproduce

You know the gig

### Screenshots and Additional Info

![17292697146006838352539282487299](https://github.com/user-attachments/assets/d26a8037-758a-4120-97c9-2d1d468647bd)
No snow 😞

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
PS, not even had 1 glass of wine yet...

**Comment by JustinHillTylerTech** [comment]
We are still in October. I'm pretty sure this is coded to only start appearing late November/Early December so you don't have to enable/disable in the settings all the time.

**Comment by jurialmunkey** [comment]
You're waaaayyyy too early! It's date based - starts in December

**Comment by adamosborne83** [comment]
> You're waaaayyyy too early! It's date based - starts in December

Spoil sport 🤣

**Comment by L0bsang** [comment]
Was wondering about this the other day haha. 

Good to know it appears in December, I was still on Arctic Horizon 2 last year so only saw it in screenshots, looking forward it this year. :)
