### ISSUE TITLE
Problems with Movie Info Widgets

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse.2#149]
### Skin section

Widgets

### Current Behavior

Hi Jurial,
In the Movie Info Widgets there are sometimes large black areas, like here : 

![Capture d'écran 2024-10-18 200116](https://github.com/user-attachments/assets/dd8ae3ea-7188-43ff-a83b-cea709fb0e95)

And sometimes I also have a Widget called "Widget" that seems inconsistent, that doesn't seem to have any connection to the movie the information is about.

![image](https://github.com/user-attachments/assets/7bc976dd-59bb-4967-8d61-366b8fd9de31)

### Expected Behavior

Widgets must follow each other, without empty areas.

### Steps To Reproduce

Go to a movie's information, then scroll down and cycle through the Widgets from top to bottom.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
i cannot reproduce this issue.

**Comment by Bindou01** [comment]
> je ne peux pas reproduire ce problème.

For the "black hole", this happens on only a few cases, like Alien for example in my case. I would say one movie out of 10.
While the problem of Widget named "Widget" totally incoherent is much more frequent. 1 movie out of 3 ; here it is present on A Bug's Life.

![image](https://github.com/user-attachments/assets/7ca71094-0dfd-4b15-b1ba-99e2a5e72f94)

![image](https://github.com/user-attachments/assets/0ef38eee-7b23-4139-ae57-aab6d30263dc)

**Comment by Bindou01** [comment]
Hi @jurialmunkey,
I don't know if it's intentional on your part but this bug has disappeared with one of your latest updates. I still had the problem a few days ago, and today I checked, everything works perfectly. So I'm closing this bug.

Thank you so much !
