### ISSUE TITLE
:bug: Problem local trailer with emby server

### ISSUE THREAD

**Issue by ntls2000** [jurialmunkey/skin.arctic.fuse.2#153]
### Skin section

Video Info Dialog

### Current Behavior

Hi,

Since AF1 to AF2, i have problems with trailers movie when i open movie information.
Background video no working, i have a big box for launching trailers

I use only local trailers and emby for Kodi addon
I don't have this problem with AF1

last update 2.0.17

### Expected Behavior

Playing local trailer from emby server in background video

### Steps To Reproduce

Open video info

### Screenshots and Additional Info

![Screenshot_20241017-152924](https://github.com/user-attachments/assets/84fa0ecc-98b4-4cfe-b067-dc06a2295387)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Not a bug. Intentional.

See https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/23
