### ISSUE TITLE
:bug: Move to front of widget, if new content is added

### ISSUE THREAD

**Issue by GitThisAcc** [jurialmunkey/skin.arctic.fuse.2#160]
### Skin section

Widgets

### Current Behavior

For example, if the `New Tv Shows` widget is displayed and the first item is selected:
![view1](https://github.com/user-attachments/assets/2fd7443c-dcdc-470a-9cdd-34bc8d721b79)

When [Jellyfin-Kodi](https://github.com/jellyfin/jellyfin-kodi) refreshes and finds new media, the widget refreshes and adds it to the front (red):
![view2](https://github.com/user-attachments/assets/b410b154-a4cd-4823-aeb7-d9079338e0d9)

### Expected Behavior

I would like the cursor/selector to automatically jump to the front when new content is added, if possible:
![view3](https://github.com/user-attachments/assets/22159bc9-ddac-435e-b9f5-07d0e9e8cf88)

### Steps To Reproduce

1. Select/hover over any item in a widget.
2. Add new media for that widget (movie, show, etc). In my case, via Jellyfin.
3. Wait for the content/widget refresh.
4. The new item(s) should now appear on the left side, slightly out of frame, if sorted like the default "new shows playlist". 

### Screenshots and Additional Info

I tested this with the default skin, `Estuary`, using the `Recently added episodes` widget. In this case, the cursor remains on the selected item, but the newly added items on the left are displayed correctly and not hidden:
![view4](https://github.com/user-attachments/assets/c61f6eab-9984-43cc-b470-8e950302f754)

Kodi v21.1.0
Fuse v2.0.18

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This behaviour is not possible for the skin to control and is hard coded in Kodi. 

Kodi will always force focus to the same item in the list (assuming it still exists after the container refreshes). There is no way for a skin to send focus to the start of the list. You would need to make a feature request for Kodi to change this behaviour.

The only reason for the *slightly* different behaviour in Estuary is that widgets in Estuary are "list" controls whereas Arctic Fuse uses "fixedlist" controls -- that is, a fixedlist control has a "fixed" position (in this case, the first position) where it scrolls from and only allows the position to move at the end of the list, whereas a list control works the opposite way in that it freely allows movement but only *scrolls* once reaching the boundary. 

The exact same issue can occur in Estuary, it just depends on which way you were scrolling from before the widget refreshed.
