### ISSUE TITLE
In the Search hub, the back key does not move up the Widget stack.

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse.2#162]
### Skin section

Widgets

### Current Behavior

In the Search hub, the back key does not move up the Widget stack.

![image](https://github.com/user-attachments/assets/3d1e4ced-084c-44b9-bfdd-089971b0c6ff)

The good news is that this will be the last bug I report, because I haven't noticed any other bugs than the ones I've already reported. :D

Thanks for everything Jurial !

### Expected Behavior

Same behavior as other hubs.

### Steps To Reproduce

Browse the Widget list in this view, and use the back key to observe its inappropriate behavior.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This behaviour is intentional.

Resetting to top is not the behaviour of the back key. Resetting to the top is the behaviour of the category button gaining focus.

The only reason other hubs/home reset to the top of the group is because back sends focus to the category button which then resets the group to the top.

**Comment by Bindou01** [comment]
Now that I understand the desire not to go up the Widget stack I understand better the origin of the "real" problem.

-> If you display several Widgets in "simple/base" view, that you place your selector/cursor on the lowest Widget, and that you navigate in the middle of this Widget. Observe carefully the behavior of the return key: the selector is not placed at the beginning of the Widget, but at the beginning of the upper Widget. And contrary to what I believed, this is not specific to the Search Hub, it happens on all Hubs.

I think it is legitimate to answer again here, if I am wrong, forgive me, no need to block the conv, I will understand.

For the rest, thank you for taking the time to test my suggestions. I hope that these will be unanimous, because personally, I find them convincing, especially this aspect:

![image](https://github.com/user-attachments/assets/b59a9924-0ec9-4b5a-aa84-1739c8774f26)

As for the resolution of bugs, good work. The result is impressive.

See you soon,
Bindou

**Comment by jurialmunkey** [comment]
The behaviour you are describing is a kodi bug with grouplists and only occurs on the last widget. It is due to the positioning of the last widget being handled differently.

If you enable mouse friendly widgets in the settings this bug will no longer occur.

**Comment by Bindou01** [comment]
Thanks for this tip that I didn't know. It actually works perfectly now. I'll come back one last time to the desired behavior which consists of not going up the Widget stack. I completely understand the approach, but I just wanted to let you know that this could lead to a form of confusion, especially when you leave the Search hub and come back to it several hours later. The low position of the Widget stack is a display similar to what happens when a search returns no data in the library, which can therefore be misleading.

![image](https://github.com/user-attachments/assets/d4100e23-ba75-4a83-81c7-5163fe268111)

But I imagine that this choice must have other advantages depending on the configuration, so I understand, but I still wanted to let you know in case a compromise could exist. This is just a detail!

Have a nice day.

PS : That said, the "cube" indicators on the cover may indicate otherwise. So let's drop it.
