### ISSUE TITLE
Spotlight return goes to settings not top bar

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#17]
### Skin section

Widgets

### Current Behavior

If I press return on my Fire TV remote on a widget it goes to top bar, which is fine. BUT if I press the return button whilst in spotlight, it goes to settings. 

### Expected Behavior

To go to top bar

### Steps To Reproduce

See video, hope that explains 

### Screenshots and Additional Info

https://github.com/user-attachments/assets/0799b1d5-32ab-4181-9a95-c364a0fb6095

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
^^ This will also fix the info dialog issue.
