### ISSUE TITLE
:bug: Short Description

### ISSUE THREAD

**Issue by ninopina** [jurialmunkey/skin.arctic.fuse.2#177]
### Skin section

Widgets

### Current Behavior

If you complete a season, it does mark the views, but if you watch a single episode, it does not mark it until you have seen the entire season. I hope that with an update it will be solved, thank you very much

### Expected Behavior

When you watch an episode mark it as watched

### Steps To Reproduce

Click

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is controlled by Kodi, not the skin.
