### ISSUE TITLE
Artwork bug with alternate versions on video info dialog

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse.2#197]
### Skin section

Video Info Dialog

### Current Behavior

When going to alternate versions from the video info dialog, the artwork of the default version is incorrect. It often doesn't show the poster at all and instead of the landscape artwork it shows a frame grabbed from the video.

### Expected Behavior

Have all versions show their correct poster and landscape artwork.

### Steps To Reproduce

1. Go to video info dialog of a movie that has alternate versions
2. Pull up the side menu and go to Alternate Versions
3. Notice how the artwork of the default version is incorrect

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Are you sure this doesn't happen in Estuary too? It sounds like a Kodi bug, not a skin bug.

**Comment by Aemstel2** [comment]
Yes you are correct. It also happens in Estuary. It doesn't happen in Fuse 1, that always showed the correct landscape artwork. That's why I didn't check Estuary. Sorry about that.

edit: Also, when pulling up the alternate versions dialog from a movie context menu, where you can now see big posters with codec info below (very nice!), that does always shows the correct posters.

**Comment by jurialmunkey** [comment]
> Yes you are correct. It also happens in Estuary. It doesn't happen in Fuse 1, that always showed the correct landscape artwork. That's why I didn't check Estuary. Sorry about that.

In that case, it will be related to this known issue: https://github.com/xbmc/xbmc/issues/24371

If in AF1 you're talking about the widget, then, yes, that'd be fine because that's just the path for the versions directory (i.e. its the same as when you have the setting to open versions as a folder) -- but the issue here is different because the dialog in that opens from the button in info is the management dialog, not the selector or directory.

**Comment by Aemstel2** [comment]
Ok. Wow that's an old issue. Hopefully it will get sorted sometime.

In AF1 I meant the video info dialog as well:

![alt-versions](https://github.com/user-attachments/assets/bb347c39-4576-418e-bd60-5abe3f17ce90)

The landscape artwork was always correct there.

**Comment by jurialmunkey** [comment]
> In AF1 I meant the video info dialog as well:

Yeah this is what I was talking about above. That widget is the same directory as when you open versions as a folder, which is why it doesn't have that issue (and I assume the select dialog pulls up the same directory too).

The button launches the management dialog which is where the problem is.

**Comment by Aemstel2** [comment]
I see. Would it not be possible to do the same in Fuse 2 then?

**Comment by jurialmunkey** [comment]
Isn't that effectively what the version select dialogue does anyway? I didn't think there was much value in a widget where you'd have to scroll down to find it when you could just hit play and see the versions immediately.

**Comment by Aemstel2** [comment]
Ah yes, I see what you mean. It's all because of the "Media Settings - Videos - Default select action" setting. When that is set to the default "Play", I agree there is no reason to have the versions in the video info dialog.

But I really like to go the movie info dialog first so I've always had that set to "Show information". That is why I miss the nice version select in the movie info dialog that AF1 had, because with this setting it bypasses the cool version select with the big posters you made in AF2.

**Comment by jurialmunkey** [comment]
Oh I didn't realise that this option doesn't work from inside the info dialog. I think I might be able to fake the dialog, let me see.

**Comment by Aemstel2** [comment]
Very nice, thanks!
