### ISSUE TITLE
🐛 Global widgets customization button

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#199]
### Skin section

Widgets

### Current Behavior

Hello Jurial,

In the new hubs customisation page, I can't find a way to customize the global widgets. They appear in the hub but can't be customized in the customization page.

### Expected Behavior

There should be a global widgets button to customize or create global widgets in hubs

### Steps To Reproduce

Go to customize hubs
Try to create a global widget for any hub

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Rinicko100** [comment]
I noticed there's a global widget button at the side under "Hub options. "... However,  this is only when you have one category... I think this would be better at the front, directly under "Edit categories and widgets"

**Comment by jurialmunkey** [comment]
> I noticed there's a global widget button at the side under "Hub options. "... However, this is only when you have one category...

Yeah as soon as you made the issue I remembered why I had that button in the main window as well - completely forgot about having setups with only Spotlight + Global Widgets.
