### ISSUE TITLE
🐛 Basic widgets not showing 

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#200]
### Skin section

Widgets

### Current Behavior

In the widget customization page, basic widgets to not appear after being added

### Expected Behavior

Basic widgets should populate the list as they're being added

### Steps To Reproduce

Go to customize hubs 
Select basic widgets for any hub
Edit widgets
Add any item

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by drout69** [comment]
I see the same behavior on v2.1.4 on Win11 PC. Compared to an earlier version of the skin I was messing around with, it feels like 2.1.4 has 'lost' the top level hub management. Skin Settings now seems to dump you a layer deeper into the hub configuration.

**Comment by jurialmunkey** [comment]
It hasn't lost hub management. The screen has been simplified to be *only* hub management and you need to click into configure the items

**Comment by jurialmunkey** [comment]
People were complaining it was too complicated and overwhelming, so it was simplified. Now you just click the hub you want to configure the items for and the dialogue pops out to let you customise the items.

The base windows shows you the settings for each hub and nothing more

**Comment by Rinicko100** [comment]
> People were complaining it was too complicated and overwhelming, so it was simplified. Now you just click the hub you want to configure the items for and the dialogue pops out to let you customise the items.
> 
> The base windows shows you the settings for each hub and nothing more

I understand the simplification, and it's much more straightforward now for new users... but there is a bug as the widget items don't come up for the basic layout. So there's no way to edit or add widget items... When I click "Edit widgets" it comes up empty, despite having widget items there, and when I add an item, it doesn't show up 🤔🤔🤔

**Comment by jurialmunkey** [comment]
Ohhh! I understand you now. I thought you were talking about how there used to be a preview shown there. But I get you now - the button is not editing the correct menu config containing the basic widgets.

**Comment by Rinicko100** [comment]
> Ohhh! I understand you now. I thought you were talking about how there used to be a preview shown there. But I get you now - the button is not editing the correct menu config containing the basic widgets.

Yeah, exactly that.

**Comment by jurialmunkey** [comment]
Was just a small typo on my part. 

Also fixed up the clicking the hub window selector button to open in the correct place when basic mode is selected
