### ISSUE TITLE
No longer able to change view types for widgets or change limit with the new update. 

### ISSUE THREAD

**Issue by 43v3rLoCo** [jurialmunkey/skin.arctic.fuse.2#203]
### Skin section

Widgets

### Current Behavior

The option to change view types like portrait or card are no longer avaible when creating widgets with the latest update.  
Edit - I can see the options in the hubs, but not in the "Home" section. 

### Expected Behavior

Before the update all option were avaible to edit widgets. 

### Steps To Reproduce

Go to edit widgets and you can see that no options are avaible. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by derrgoo** [comment]
I see it. Nothing has changed. 

![image](https://github.com/user-attachments/assets/8480a96a-2114-4133-86d7-c26a5b2b147d)

**Comment by 43v3rLoCo** [comment]
I only see them in other hubs but not in the home hub. 

![20241025_231510](https://github.com/user-attachments/assets/b5eece53-322e-4c6b-8f0b-230c1fb5733e)

![20241025_231446](https://github.com/user-attachments/assets/b7fd7600-e696-437b-8198-3f78913b1aa8)

**Comment by derrgoo** [comment]
I am using classic there to show. Are you at the latest update. You may want to reinstall the skin again. Seems strange.

**Comment by 43v3rLoCo** [comment]
Yes I am on Arctic Fuse 2 version 2.1.4

**Comment by jurialmunkey** [comment]
Yep I can reproduce. Not sure what happened there as I didn't touch that part of the dialog but possibly I've made a typo somewhere breaking something.
