### ISSUE TITLE
🐛 Global widgets button opening the wrong edit page

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#206]
### Skin section

Widgets

### Current Behavior

The global widgets button is opening the edit page for basic widgets instead of the regular global widgets page. My global widgets are there but I'm unable to reach the edit page for them

### Expected Behavior

Global widgets button should open the global widgets page

### Steps To Reproduce

Go to hubs customisation page
Navigate to a hub
Click on edit global widgets

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ha, I'm a dummy. Had my basic widgets setup as the same set of widgets as my global widgets in the hub I was testing in, so I didn't notice at all.

**Comment by Rinicko100** [comment]
> Ha, I'm a dummy. Had my basic widgets setup as the same set of widgets as my global widgets in the hub I was testing in, so I didn't notice at all.

Honest mistake.... you're a one man army after all 😂😂
