### ISSUE TITLE
Widget initialisation screen bug? 

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse.2#207]
### Skin section

Widgets

### Current Behavior

So I've noticed with the most recent update when we exit playback of something the same screen that appears at launch re appears "widget initialisation" and all the widgets re load, this never happened prior to the latest update, the widgets are already pre loaded when returning back to the widget screen. 

### Expected Behavior

When playback is finished and we return back to widget screen they were already loaded. 

### Steps To Reproduce

Exit playback 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I haven't changed how this is handled. All it does is check if the first widget ID NumItems=0 and Container(ID).IsUpdating. 
For home or basic hub, first widget is first widget of first category.
For advanced hub with spotlight, first widget is spotlight.

There's nothing else to it. If the splash displays then it means your first widget has 0 items and is currently updating.

**Comment by etgecata** [comment]
I have exactly the same problem with version v2.1.6. Upon completion of playback, all widgets are reloaded. With previous versions of the skin, I didn't have this problem. I reverted to version v2.1.4 and this problem does not exist.
I am using hub 1001 -combine widget. I don't use a spotlight.
Hope you find the problem because with this constant loading of widgets it is impossible for me to use your lovely skin.

**Comment by jurialmunkey** [comment]
> constant loading of widgets

Skins don't control whether widgets load. The skin only controls whether or not you can *see* that it is loading.

You can turn off the initialisation splash in the skin settings.

> combine widget.

Using static or dynamic list?

**Comment by etgecata** [comment]
I am uploading pictures of the settings. I do not use Use combined list. I only use Combine widgets.
You can turn off the initialisation splash in the skin settings - I saw where the setting is. I activated it. No change-Upon completion of playback, all widgets are reloaded.
![20241027_083420](https://github.com/user-attachments/assets/979f6fc9-4456-4554-ba22-e007903361bb)
![20241027_083444](https://github.com/user-attachments/assets/2dabddf1-7c87-4101-946d-512046db7ad0)
![20241027_083456](https://github.com/user-attachments/assets/cd33eca4-1c15-4a30-a1c2-f8193b9aa9e2)

**Comment by jurialmunkey** [comment]
It is important to understand that Kodi reloads *all* widgets after starting or stopping playback. There is nothing the skin can do about this behaviour.

The only difference the skin make is whether or not you *see* that the widgets are reloading but even if the loading spinner is hidden it does not mean that the widgets are not reloading.

**Comment by JFG1000** [comment]
I reverted back also, we never see this reload before. They were all ready to use. @jurialmunkey please could consider testing in comparison of the versions, that way you will see for yourself. Amazing work you have done but this is quite frustrating

**Comment by etgecata** [comment]
I understand that. But now I reverted to v2.1.4 again and I don't have this problem. Kodi version is the same, everything is the same. The only difference is the skin version-v2.1.4. I am uploading a video for version v2.1.4 and for version v2.1.6:

https://mega.nz/file/rVkFgajR#QIDG-LD0iZU4CpOuTyN-DtThojBvsJsMV9n9GZ3NRX8

https://mega.nz/file/md9BHIJJ#v2LryQ7EuFWDDBUqfSMQuVWrBCwfSzPCtWKN54AGS0E

With the latest version v2.2.1 it is the same as with version v2.1.6.

**Comment by JFG1000** [comment]
> I understand that. But now I reverted to v2.1.4 again and I don't have this problem. Kodi version is the same, everything is the same. The only difference is the skin version-v2.1.4. I am uploading a video for version v2.1.4 and for version v2.1.6:
> 
> https://mega.nz/file/rVkFgajR#QIDG-LD0iZU4CpOuTyN-DtThojBvsJsMV9n9GZ3NRX8
> 
> https://mega.nz/file/md9BHIJJ#v2LryQ7EuFWDDBUqfSMQuVWrBCwfSzPCtWKN54AGS0E
> 
> With the latest version v2.2.1 it is the same as with version v2.1.6.

Really appreciate the work jurial has don't for us on this amazing skin but currently what is happening is putting me off updating any further

**Comment by etgecata** [comment]
And I will stay on version v2.1.4 for now until a solution to this problem is found. With this widget reload, it's impossible for me to use this lovely skin.

**Comment by jurialmunkey** [comment]
I have not changed any code in the hubs windows between 2.1.4 and 2.1.6 other than the addition of an icon mode. The skin code is not included unless the option is enabled so there is no reason it should have any impact.

This is the commit https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/0dcfcf69b4d680468b4727bd98028dd1e999eeb3

If this is the culprit then this highlights an issue within Kodi's skinning engine.

**Comment by etgecata** [comment]
How do we run a test to see if the issue will be resolved?

**Comment by JFG1000** [comment]
> I have not changed any code in the hubs windows between 2.1.4 and 2.1.6 other than the addition of an icon mode. The skin code is not included unless the option is enabled so there is no reason it should have any impact.
> 
> This is the commit [0dcfcf6](https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/0dcfcf69b4d680468b4727bd98028dd1e999eeb3)
> 
> If this is the culprit then this highlights an issue within Kodi's skinning engine.

I respect what your saying and thankyou for explaining then, I'll personally have to stay on 2.1.4 and hope that further down the line kodi plays ball then

**Comment by jurialmunkey** [comment]
> I respect what your saying and thankyou for explaining then, I'll personally have to stay on 2.1.4 and hope that further down the line kodi plays ball then

You will be waiting a long time if the commit is the cause of the problem because it highlights a significant issue in the skinning engine which I will never be able to solve myself.

**Comment by JFG1000** [comment]
> > I respect what your saying and thankyou for explaining then, I'll personally have to stay on 2.1.4 and hope that further down the line kodi plays ball then
> 
> You will be waiting a long time if the commit is the cause of the problem because it highlights a significant issue in the skinning engine which I will never be able to solve myself.

I understand. It really pisses me off when kodi behaves like this, as good as a media centre it is it loves to cause a problem

**Comment by jurialmunkey** [comment]
> How do we run a test to see if the issue will be resolved?

I need to find the specific commit the issue started occurring in.

You can see all the commits that were done between the two versions here:
https://github.com/jurialmunkey/skin.arctic.fuse.2/compare/v2.1.4...v2.1.6

It's just a matter of going back through the versions  (up is older down is newer) and finding the specific commit where the issue no longer occurs. The one after whatever that commit is will be the code that introduced the issue

You can download a specific commit by adding the commit hash to the tree and then using the "code" button to download a zip
https://github.com/jurialmunkey/skin.arctic.fuse.2/tree/75f011d0b2c704ba5b762208a7b6e769768e9e7f

e.g. you can get this tree location by clicking the `< >` button on the right of the commit
![image](https://github.com/user-attachments/assets/93cf75b2-e8a1-423f-8a8c-46d61f3fa5b2)

Then use the code button to download the zip to install it

![image](https://github.com/user-attachments/assets/1ab6502f-df2f-4a15-861c-2c7e063cc12b)

**Comment by JFG1000** [comment]
@etgecata can you report back with any results please mate

**Comment by etgecata** [comment]
I hardly have time today. Another issue is that there are many commitments and I don't know if I will be able to handle it alone.

**Comment by jurialmunkey** [comment]
In some tests I think it might be this commit https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/7b7e8a79f80ba2850278fc86e3715c8fadaa8f39

It makes absolutely no sense at all why it would cause this issue but it seems to be the one.

Can you please try this version which reverts that commit and see if it makes a difference
https://github.com/jurialmunkey/skin.arctic.fuse.2/archive/refs/heads/revertcommit.zip

**Comment by JFG1000** [comment]
> In some tests I think it might be this commit [7b7e8a7](https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/7b7e8a79f80ba2850278fc86e3715c8fadaa8f39)
> 
> It makes absolutely no sense at all why it would cause this issue but it seems to be the one.
> 
> Can you please try this version which reverts that commit and see if it makes a difference https://github.com/jurialmunkey/skin.arctic.fuse.2/archive/refs/heads/revertcommit.zip

Yes give me a few I'll test and report back, thankyou jurial

**Comment by etgecata** [comment]
Perfect with this version everything is fine. I am very happy to continue with arctic.fuse.2.
Let me ask one more thing.

Can you introduce this improvement I wrote about in discussions:
https://github.com/jurialmunkey/skin.arctic.fuse.2/discussions/105

Like one more thing that I miss a lot from arctic.fuse.1- edit categorie.
I don't know how to describe it, so I'll upload a picture:
![20241027_121124](https://github.com/user-attachments/assets/8d0dc47b-030c-4309-a614-6ccb69f8a596)
![20241027_121211](https://github.com/user-attachments/assets/09763944-d05c-45e6-8a0d-bbbd5f330904)
![20241027_121300](https://github.com/user-attachments/assets/7f100e76-e7fa-43dd-958f-592def555abf)

**Comment by jurialmunkey** [comment]
Please keep on topic.

**Comment by JFG1000** [comment]
@jurialmunkey tested and happy to report all seems ok now, thankyou so much

**Comment by etgecata** [comment]
Thank you from the bottom of my heart. I apologize for writing off topic. But I like the skin very much. I just miss some features from Arctic Fuse.

**Comment by jurialmunkey** [comment]
> @jurialmunkey tested and happy to report all seems ok now, thankyou so much

Yeah I was pretty reliably able to create the issue prior to that revert and not at all afterwards.

Still makes absolutely no sense to me *why* it is causing it though. It seems like a "perfect storm" sort of scenario of very specific conditions triggering some very obscure bug which the skin engine cant deal with so it just reloads the entire skin instead.

That seems to match what is happening in the video -- it looks like the *whole* window is reloading as if you'd hit the ReloadSkin() command, not just the widget container loading new content.
