### ISSUE TITLE
New style home side menu Does not show content 

### ISSUE THREAD

**Issue by taiseer999** [jurialmunkey/skin.arctic.fuse.2#209]
### Skin section

Widgets

### Current Behavior

New style home side menu In the latest update is not displaying anything unless Focus is on options. 

### Expected Behavior

Show something 

### Steps To Reproduce

Move focus to the left nothing appears unless  moving to the left from options 

### Screenshots and Additional Info

![IMG_5091](https://github.com/user-attachments/assets/739d0227-8d65-465f-b8e3-cc9805b4faad)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
`Customise hubs > Home > {Category} > Edit items`

Each item has its own menu.

**Comment by taiseer999** [comment]
Thanks you are the best
