### ISSUE TITLE
:bug: home widget initial focus, locked out

### ISSUE THREAD

**Issue by homeslixe** [jurialmunkey/skin.arctic.fuse.2#214]
### Skin section

Widgets

### Current Behavior

Using on media device, apple tv. Bug likely effects other media devices that are not PC. 

When selecting initial home focus to widgets, the side menu becomes inaccessible as widget items cycle infinitely when cycling to the left. cycling to the left should allow access to menu bar, however it instead infinitely cycles witdget items. 

The nature of navigating kodi on media devices, such as apple tv, limits actions that can be performed when comparing to PC navigation. Eg/ back action will only work as intended from sub menus/libraries to navigate to a previous menu. From the home hub, the back action exits Kodi, preventing any access to the home menu bar. Left action cycles infinitely as previously mentioned.

This results in Kodi being locked out of any settings/other menus and searching, with access only to widgets already created on the home hub. Currently the only way to fix this is a complete reinstall of Kodi on the media device.

### Expected Behavior

See above description

### Steps To Reproduce

See above description

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
What is the bug here? The setting works as expected - it sets focus to the widgets and loops them. That is the intended behaviour.

What does your lack of a back key (a basic and expected key) have to do with the skin?

**Comment by homeslixe** [comment]
Intended or not, infinite cycle with no access to an options menu from the home hub breaks functionality on non PC builds. System breaking functions are considered bugs. If an option for infinite left key cycle to be turned off from home hub widget focus on start is not possible, please consider adding down key for options from af1. This failsafe option would eliminate the issue

**Comment by jurialmunkey** [comment]
Or you could just change your keymap so that you have a Back action or a way to access the Power menu. 

Kodi allows customisation of your keymap (and if there's some issue on AppleTV preventing this then you need to discuss that with Kodi devs who work on AppleTV). 

Back key is a basic navigation key and the skin should not have to suffer because you're missing it.
