### ISSUE TITLE
:bug: Clock overlays Home hub options button

### ISSUE THREAD

**Issue by L0bsang** [jurialmunkey/skin.arctic.fuse.2#220]
### Skin section

Clock and Notifications

### Current Behavior

When using a custom hub (1101 in this case) as a home screen, the options button is overlaid by the clock if enabled. 

This has been happening for a while (probably since options button was added to hubs) but I see no others reporting it. It is possible this only happens on my setup, or simply that no one else has this combination of options. 
I did copy my home hub over from Arctic Fuse initially, and was aware it may cause weird behavior.

### Expected Behavior

I can see how it is supposed to work if I load into a hub, the clock bounces away from the options button and there is no overlay. 

However if I then select that same hub as homescreen, this behaviour no longer occurs, the clock stays in place, options screen is selected below it.

### Steps To Reproduce

1. Use a Hub as the homescreen
2. Enable 'Home > Search and options' so that there is an options button on the homescreen hub
3. Scroll across your categories onto the options button, note the overlay (picture attached)

### Screenshots and Additional Info

![image](https://github.com/user-attachments/assets/b40a366d-d227-4b89-a6ff-bca0b71b438d)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by L0bsang** [comment]
@jurialmunkey 

This issue recurs on the advanced home screen of the latest version (2.4.11). 

After this commit: https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/ea8b839ad17d9f16901e739c66c6ede458c16dbf, we can now change the mode on the default home screen to use advanced hub features. This also changes style to horizontal/categories.

I tried it out and realized the clock is once again overlaying the options button in the advanced mode of the default hub. This issue does not affect the other hubs.

**Comment by jurialmunkey** [comment]
Ah right yeah I didn't consider that scenario. Shouldn't be too difficult to fix.
