### ISSUE TITLE
Trailers playing in background

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse.2#23]
### Skin section

Video Info Dialog

### Current Behavior

When playing a trailer in the info screen, it plays in the background.

### Expected Behavior

Trailers play either fullscreen or in the trailer box

### Steps To Reproduce

Open info from a movie, if auto trailers is enabled, it plays automatically in the background behind the text, If not enabled, scroll down to trailers and select a trailer, it will also play in the background. 

### Screenshots and Additional Info

https://github.com/user-attachments/assets/cdf108dd-d4e6-4adb-847d-6bbbc4da0059

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Playing from the trailers list works fine for me.
