### ISSUE TITLE
Settings menu navigation issue

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#230]
### Skin section

Widgets

### Current Behavior

In the general kodi settings menu, for example, system settings or service settings or interface settings etc. Moving up in the list will take you to the toggle to switch between Expert and Basic, then moving up again will take you back to the top. 

### Expected Behavior

I think this is meant to be a contained loop between the first and the last setting option, then moving down from the last setting will take you to the Expert and Basic switch... as this is the way it is in default Kodi.

### Steps To Reproduce

Navigate to settings
Go to PVR or Interface or Service or any settings 
From the first option, move up, then try to move up again.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I dont think the behaviour in Estuary is any better, just different. If anything, I find it weirder because it loops at the top but not the bottom.

**Comment by Rinicko100** [comment]
> I dont think the behaviour in Estuary is any better, just different. If anything, I find it weirder because it loops at the top but not the bottom.

Yeah, I also don't think it's any better. It's a pretty confusing loop behavior. I just thought it was what you were going for.

Personally, I think a general loop would be better,  though I don't know if that would be confusing for new users who may not be able to recognize the button as a switch.

**Comment by jurialmunkey** [comment]
> Personally, I think a general loop would be better

Well that's how it worked originally. It looks like the internal values for the category button IDs changed in Omega (not sure if it was in 21.1 or 21.0 but they changed by -100).

Easy fix.

**Comment by Rinicko100** [comment]
> > Personally, I think a general loop would be better
> 
> Well that's how it worked originally. It looks like the internal values for the category button IDs changed in Omega (not sure if it was in 21.1 or 21.0 but they changed by -100).
> 
> Easy fix.
> 

I see.. Well, that's good then
