### ISSUE TITLE
:bug: Music OSD always displays Clearlogo if available

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse.2#231]
### Skin section

Other

### Current Behavior

Since commit 4ece9a9 I've noticed that the Music OSD always displays the Clearlogo for the artist (if available) rather than the name in text, irrespective of the setting Interface / Style - Title being Text or Logo. Having read thru discussion #186 I thought this was the intention, but I mat be wrong!

### Expected Behavior

Music OSD should be consistent with the Interface / Style - Title setting

### Steps To Reproduce

Play track for artist with Clearlogo

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by OfficerKD637** [comment]
Maybe adding an additional `Skin.HasSetting(TMDbHelper.EnableCrop)` [here](https://github.com/jurialmunkey/skin.arctic.fuse.2/blob/4ece9a9bc99e5aef5d5057eced318c2e94033dfb/1080i/Includes_OSD.xml#L1073) might fix it?

**Comment by berkhornet** [comment]
@OfficerKD637 many thanks for that PR. I've made the changes suggested and confirm that they work for me!

**Comment by OfficerKD637** [comment]
Awesome! I added a second commit later to the PR so make sure you have both of them (should have been one commit in the first place but I'm a dummy🤦)
![image](https://github.com/user-attachments/assets/3c0e86c0-e4fb-4cc7-85ff-0ffe3fe3a756)

**Comment by berkhornet** [comment]
Thanks - I noticed that. All looks good.
