### ISSUE TITLE
Wrong initial position of cursor/selector in Settings->Extension

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse.2#242]
### Skin section

Paramètres->Extension

### Current Behavior

The cursor is always placed on the third line "Manage dependencies" while it is a priori more common to go to the first "My extensions".

### Expected Behavior

Cursor on the first line?

### Steps To Reproduce

Reload skin and enter settings categories:  Extensions

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I have no idea what this is referring to

**Comment by Bindou01** [comment]
And with this extract? https://youtu.be/Suqq3FjcoHM
It's a detail, but it's important when you often tinker in this area ^^

**Comment by jurialmunkey** [comment]
I can't do anything about this. It is due to the way Kodi first loads the window.

Once the window has loaded, if you go out and then back in you will notice that the focus lands on the first item.

**Comment by Bindou01** [comment]
@jurialmunkey 
That's weird, it doesn't happen in the Estuary Skin. Maybe because the skin never reloads, I don't know. Thanks for your answer.
