### ISSUE TITLE
Still some text elements that don't scroll properly.

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse.2#243]
### Skin section

Other

### Current Behavior
Some texts scroll by themselves without the cursor being positioned on them, others never scroll.
![Vidéo sans titre ‐ Réalisée avec Clipchamp (1)](https://github.com/user-attachments/assets/69004baa-29ad-4c73-ac92-526e27aeca44)

### Expected Behavior

All labels should be scrollable, but only when you stand on it?

### Steps To Reproduce

...

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Kodi behaviour. Once a label has scrolled a certain amount of times it stops scrolling.
