### ISSUE TITLE
:bug: non english language does not search matching title

### ISSUE THREAD

**Issue by zdpark** [jurialmunkey/skin.arctic.fuse.2#248]
### Skin section

Other

### Current Behavior

Searching a non English title in TMDb provides accurate matching results; however, it doesn’t work when I search for a non-English title in the main menu. (Any English titles are working)

### Expected Behavior

Should return accurate matching results

### Steps To Reproduce

1. Go to Search
2. Search for a non English title

### Screenshots and Additional Info

![image](https://github.com/user-attachments/assets/f69b7834-59fd-46c6-8ced-909060b0495d)
![image](https://github.com/user-attachments/assets/e0167307-bfe3-4f4f-ba85-492ea73f450a)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Can you provide the search string as text here so I can copy paste to test?

**Comment by zdpark** [comment]
Sure mate. Thanks for your prompt response.

venom 
베놈

**Comment by zdpark** [comment]
The same issue occurred again after the update.
