### ISSUE TITLE
When playing movie with multiple versions from video info dialog it does not auto focus on default version

### ISSUE THREAD

**Issue by Aemstel2** [jurialmunkey/skin.arctic.fuse.2#259]
### Skin section

Widgets

### Current Behavior

When on the video info dialog of a movie with multiple versions, after pressing play, the version select screen does not focus on the default version. There is also no indicator showing which is the default version. It does focus on the default version when playing directly from the library.

### Expected Behavior

Focus on the default version or have some kind of label to indicate which one is the default version. It's handy to be able to see which version is set as default, because that is basically the preferred version. Can't always remember which one that was.

### Steps To Reproduce

1. Go to video info dialog of movie with multiple versions.
2. Press play
3. Notice that the default version is not automatically focused and there is also no indicator/label for it

(of course the default version could be focused by accident, so you may need to do these steps on multiple movies to see it not working)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is because the dialog is faked so it is working the same as the widget in AF1 (which also doesn't start on the default).

I don't think there is any solution here. There's no way to open the real selector from the info dialog.

**Comment by Aemstel2** [comment]
Right, I understand. It's also not a big problem, since the version can also be seen on the main info dialog, like in AF1.
