### ISSUE TITLE
:bug: TMDB helper not returning information from Kodi local library even when configured.

### ISSUE THREAD

**Issue by Infrared-prime** [jurialmunkey/skin.arctic.fuse.2#264]
### Skin section

Video Info Dialog

### Current Behavior

When playing any video and you click for information, TMDB helper shows nothing unless you are connected to the internet. All the information is already scrapped to the local library and shows when using other Arctic skins (Fuse,Horizon 2 or Reloaded). I have configured the TMDB helper addon to check Kodi local library, but it still won't return any information unless it's currently online.

### Expected Behavior

As long as your movie/TV video files are already scrapped and added to Kodi Library, clicking information during playback should return the scrapped information regardless of current online connectivity.

### Steps To Reproduce

Ensure your video is already scrapped and added to Kodi Library.
Ensure you aren't presently connected to the internet.
Playback said video and click for information during playback.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Infrared-prime** [comment]
![PXL_20241102_170854216 MP](https://github.com/user-attachments/assets/4d53ef24-5c53-4a1c-be09-2817a22786c2)

**Comment by Infrared-prime** [comment]
![PXL_20241102_170937654 MP](https://github.com/user-attachments/assets/bcddfc93-e1b8-4731-b38c-4cc4af2e5f62)

**Comment by jurialmunkey** [comment]
Tmdbhelper requires internet access to work correctly.

**Comment by Infrared-prime** [comment]
Seen 👍🏾.

Thank you very much for the clarification, it's really appreciated.

**Comment by Infrared-prime** [comment]
Seen 👍🏾.

Thank you very much for the clarification, it's really appreciated.
