### ISSUE TITLE
Some Chinese characters are displayed as garbled text.

### ISSUE THREAD

**Issue by shawmsean** [jurialmunkey/skin.arctic.fuse.2#275]
### Skin section

Fonts and Languages

### Current Behavior

When the language is set to Simplified Chinese and the font is set to CJK, some Chinese fonts may display garbled text.
<img width="944" alt="中文乱码" src="https://github.com/user-attachments/assets/70ff8e90-dc16-4ba4-be80-1ba4266513c0">

### Expected Behavior

When the font is set to CJK and the language is set to Simplified Chinese, all Chinese fonts can be displayed correctly.

### Steps To Reproduce

1.SKIN>INTERFACE-FONTS-CJK
2.REGIONAL--LANGUAGES--CHINESE(SIMPLE)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is impossible to address.

There is an upper limit for true type fonts at 65,535 glyphs (16bit integer maximum). 

The CJK font set already uses all of these 65,535 glyph spaces and so cannot support any further characters. Some characters will not be supported.

Kodi does not support fallback fonts and so this will continue to be an issue until Kodi changes how it handles fonts.
