### ISSUE TITLE
Few Errors and Warnings in log

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#28]
### Skin section

Widgets

### Current Behavior

Here's a log just wondering if anything for concern.

### Expected Behavior

No errors or warnings 

### Steps To Reproduce

See log 

### Screenshots and Additional Info

Https://paste.kodi.tv/ugihawosed

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Nothing concerning but I'll fix them anyway to avoid the log spam.

**Comment by adamosborne83** [comment]
Cheers J.
