### ISSUE TITLE
Combined widget title "judders" when selected

### ISSUE THREAD

**Issue by satelly1** [jurialmunkey/skin.arctic.fuse.2#286]
### Skin section

Widgets

### Current Behavior

Using the combined widget option, when you go to the combined widget the title "judders" to the side. This only happens the first time it is selected after a restart.

### Expected Behavior

The combined widget title should not move

### Steps To Reproduce

1. Choose combined widget option and select it on home screen

### Screenshots and Additional Info

Uploading Combined Widget Title Jumping.mov…

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by satelly1** [comment]
https://github.com/user-attachments/assets/2dc7df70-2bbd-432f-b90c-f66ee197340e

**Comment by jurialmunkey** [comment]
@satelly1 @adamosborne83
Please try possible workaround in the linked PR
zip - https://github.com/jurialmunkey/skin.arctic.fuse.2/archive/refs/heads/alternative_categories_fakebutton_method.zip

I can't reproduce the issue myself (or more correctly, it happens too quickly for me to know if my changes are making a difference).

I *think* this new approach seems smoother but I really can't tell as it was never this significantly visible to me in the first place.

**Comment by satelly1** [comment]
Thanks jurialmunkey. Appears fixed now.


https://github.com/user-attachments/assets/3bd4cbdf-c822-45cd-a38f-d275ec0fd1ee

**Comment by jurialmunkey** [comment]
Excellent! Thanks for testing. Hopefully this also fixes Adam's issue. I'll merge and then can address further issues if need be.

**Comment by adamosborne83** [comment]
> Excellent! Thanks for testing. Hopefully this also fixes Adam's issue. I'll merge and then can address further issues if need be.

Thanks J

**Comment by adamosborne83** [comment]
> Excellent! Thanks for testing. Hopefully this also fixes Adam's issue. I'll merge and then can address further issues if need be.

Yea it's 100% perfect, had to install tmdbh 5.3.0 but all good my friend.
