### ISSUE TITLE
🐛 Search options leaving the search dialog

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#287]
### Skin section

Widgets

### Current Behavior

Hello Jurial, 

I'm not sure if this is intentional to allow users know, there are more search options below, but currently,  the search options when you click on "content: All" in the search window, it leaves the dialog and shows at the bottom, this makes it look a bit rough
![Kodi_20241102_041134.png](https://github.com/user-attachments/assets/14d92858-da54-4d55-b8cd-b491a6da1700)

### Expected Behavior

Search options should stay contained in the search dialog.

### Steps To Reproduce

Add more than 7 search options 
Open search window
Click "Content: All"

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Rinicko100** [comment]
> ### Skin section
> 
> Widgets
> 
> ### Current Behavior
> 
> Hello Jurial, 
> 
> I'm not sure if this is intentional to allow users know, there are more search options below, but currently,  the search options when you click on "content: All" in the search window, it leaves the dialog and shows at the bottom, this makes it look a bit rough
![Kodi_20241102_041134.png](https://github.com/user-attachments/assets/4c56fdb1-f183-45c6-ba59-7e24d31d55cb)


> 
> ### Expected Behavior
> 
> Search options should stay contained in the search dialog.
> 
> ### Steps To Reproduce
> 
> Add more than 7 search options 
> Open search window
> Click "Content: All"
> 
> ### Screenshots and Additional Info
> 
> _No response_
> 
> ### Checklist
> 
> - [X] I have made a separate issue for each bug that I am reporting.
> - [X] I have searched the issues and this bug has not been reported.
> - [X] I am using the most recent skin version.
> - [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Rinicko100** [comment]
> ### Expected Behavior
> 
> Search options should stay contained in the search dialog.
> 
I would suggest leaving only 5 or 6 items max, then adding the item count like in other areas.
![Kodi_20241102_072129.png](https://github.com/user-attachments/assets/4a7648b5-ba74-472b-ac4c-0709a9dff2fa)

**Comment by jurialmunkey** [comment]
No not intentional. Forgot to test with more than seven items and didn't realise I hadn't defined a bottom coordinate

**Comment by jurialmunkey** [comment]
Yeah I think item count with an indicator showing if there are more would be a good idea.

**Comment by Rinicko100** [comment]
> No not intentional. Forgot to test with more than seven items and didn't realise I hadn't defined a bottom coordinate

Alright... It is very well implemented
