### ISSUE TITLE
Bug in navigation by letter in the media library

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse.2#291]
### Skin section

Library

### Current Behavior

I notice an unexpected behavior when you put "Title" as the sort method and use the page selector.

![image](https://github.com/user-attachments/assets/c4e33c10-a4c8-4a00-a117-18b02ab7f64a)

When you move from one page to another, it starts by moving the numbers forward, but it does so in an anarchic order. We see the numbers moving around : 2->3->6->8->1->4->6->1->2
Then it gets to the letter A, and reviews all its variants (some even come back several times) : A->À->A->À->A->Â-> and only then do we get to the letter B.
And there is the same problem with the letter E.

Therefore, at the beginning you have to click 20 times to move forward one page, hahaha!

### Expected Behavior

1->A->B->C->D etc.

### Steps To Reproduce

..

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Kodi issue. Skin performs the nextletter action.how that works is coded into Kodi.

**Comment by Bindou01** [comment]
Hi @jurialmunkey,
Well as I expected, the Kodi team does not consider this as a problem, for now anyway.

On the other hand, after reflection, to get around this in the meantime, it would be enough for you to propose the sorting method "by file". In this way we keep the alphabetical order, and a "consistent" movement with the movement bar which will simply advance from one page to another with each click. I don't know what you think about it?

![Capture d'écran 2024-11-03 161059](https://github.com/user-attachments/assets/d38feeb6-8830-4d84-8688-80674a264db9)

**Comment by Bindou01** [comment]
Additionally, as Hitcher points out here, there is also a display issue on the Fuse 2 side which only displays one number when there are multiple numbers : 
https://github.com/xbmc/xbmc/issues/25921

**Comment by Hitcher** [comment]
@jurialmunkey is there an option to change the scrollbar behaviour to scroll through pages instead of letters?

**Comment by jurialmunkey** [comment]
> @jurialmunkey is there an option to change the scrollbar behaviour to scroll through pages instead of letters?

@Hitcher it can be added of course but that's not the issue at hand.

The issue is not skin specific. It is about action(nextletter) not behaving as expected from a user perspective.

If I am on the sortletter A and perform nextletter command, then I expect to go to B (or C or D etc depending on what's available) not via all the diacritic variations of A.

The letter A with a diacritic is still the letter A.

**Comment by jurialmunkey** [comment]
> Additionally, as Hitcher points out here, there is also a display issue on the Fuse 2 side which only displays one number when there are multiple numbers : [xbmc/xbmc#25921](https://github.com/xbmc/xbmc/issues/25921)

@Bindou01 this is not a skin problem.

The skin displays ListItem.SortLetter - whatever is in this infolabel is determined by Kodi.

> would be enough for you to propose the sorting method "by file".

This is also not a skin problem. The skin does not determine what sort methods are available.

**Comment by Hitcher** [comment]
> If I am on the sortletter A and perform nextletter command, then I expect to go to B (or C or D etc depending on what's available) not via all the diacritic variations of A.

Yeah I agree but unfortunately I have no clue as to how it works. Hopefully someone who does know will help out.

Thanks.
