### ISSUE TITLE
Combined View, flashing

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#292]
### Skin section

Widgets

### Current Behavior

Hi J,

Just playing with combined view, if you see the video, as it get towards the end it start flashing / looks like it's jumping.

### Expected Behavior

Seamless transition 

### Steps To Reproduce

Set combined with 8 'widgets' then scroll across

### Screenshots and Additional Info

https://imgur.com/a/f1Rp69O

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
I think this is similar to issue #286,

**Comment by jurialmunkey** [comment]
Yep, same underlying issue as in #286. I'll close this one.
