### ISSUE TITLE
Skin crashes from Movies to TV Shows

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#298]
### Skin section

Widgets

### Current Behavior

This might be another wild goose chase again,

But when I go from a movie to a tv show, it always crashes.

### Expected Behavior

Not to crash

### Steps To Reproduce

I'm unique, so hard to replicate 

### Screenshots and Additional Info

[kodi.old.log](https://github.com/user-attachments/files/17608101/kodi.old.log)
[kodi.log](https://github.com/user-attachments/files/17608102/kodi.log)
Old log is the crash

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by adamosborne83** [comment]
Https://paste.kodi.tv/negologuwu

Could it be something to do with tmdbh?

**Comment by jurialmunkey** [comment]
Impossible to tell anything about the cause of a crash from a log.

The only way to have any sense of the cause of a crash is with a stacktrace with debugging symbols enabled. Otherwise it is just speculation.

**Comment by adamosborne83** [comment]
> Impossible to tell anything about the cause of a crash from a log.
> 
> The only way to have any sense of the cause of a crash is with a stacktrace with debugging symbols enabled. Otherwise it is just speculation.

Sorry J,

Stack trace on android is near on impossible..... I've done a lot of research....

I've added couple more logs, if they show nothing of use, I am happy to close this issue and I'll keep messing around. 


Https://paste.kodi.tv/inutodimum

Usually after I've watched a movie and then go to a tv show


Sorry to dump on you. 

But same log using estuary, 
Disabled af2 and skin variables 

Https://paste.kodi.tv/otelalebok

**Comment by jurialmunkey** [comment]
Like I said, log can't tell me anything about the crash. Logs are good for errors or unexpected/buggy behaviour, but not crashes.

Logging can only happen *after* something has occurred. And once an application crashes, it can obviously no longer log things. All the log can tell us about is all the *successful* events that *didn't* cause a crash.

**Comment by adamosborne83** [comment]
Thanks as always J.

**Comment by adamosborne83** [comment]
You know i never listen.

But does this show anything? I have enabled additional settings for info

Https://paste.kodi.tv/diqotecezi
