### ISSUE TITLE
🐛 Side items in addon browser dialog still operate like they're on the left side

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#301]
### Skin section

Widgets

### Current Behavior

Hello Jurial, 

In the addon browser,  when you click on an addon,  the side items operate as if they are on the left side... so it takes 2 right moves to the scroll bar instead of 1, and  moving left closes the dialog instead of going to the fanart first.
![Kodi_20241103_041801.png](https://github.com/user-attachments/assets/159b4181-5fd3-4b67-ba4c-e2fc7391fd4e)

### Expected Behavior

Navigation should operate according to position.

### Steps To Reproduce

Go to the addon browser
Click on any addon
Try to access the scrollbar

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Oh I'm glad you raised this issue. I noticed it the other day but I forgot to note it down and then forgot about it.

**Comment by Rinicko100** [comment]
> Oh I'm glad you raised this issue. I noticed it the other day but I forgot to note it down and then forgot about it.

No problem!
