### ISSUE TITLE
:bug: Switching between horizontal and vertical wall appears broken

### ISSUE THREAD

**Issue by TimboZero** [jurialmunkey/skin.arctic.fuse.2#302]
### Skin section

Other

### Current Behavior

My hub was horizontal but having exceeded the 5 visible limit of this I decided to look at it in vertical orientation, changed to this under skin interface/wall orientation and set it to vertical but after rebuild it is still horizontal.

### Expected Behavior

Wall orientation switch should change hub categories from horizontal to vertical and visaversa?

### Steps To Reproduce

As described above

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by TimboZero** [comment]
Ok, my mistake and apologies for incorrect report.
Thank you for the clarification

**Comment by jurialmunkey** [comment]
No this setting is for the Wall viewtype. Nothing to do with the hubs. You can't change the orientation of hubs. All hubs have horizontal categories. The home menu only has vertical. However, you can use the "Use as home" toggle to set a hub as home (and so get a horizontal menu as home).


For reference, this is what the Wall setting changes -- it changes whether this viewtype scrolls up/down or left/right:

![wall-poster](https://github.com/user-attachments/assets/7fcc98a8-22a9-4acd-afe4-5cecfe5bab4e)
