### ISSUE TITLE
🐛 TMDb helper items clear details after return from info

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#326]
### Skin section

Widgets

### Current Behavior

In TMDb helper, when you go into the info page of a movie, then retun back, all the details of the movie is gone... The rating, summary,  artwork all gone until skin refresh.

https://github.com/user-attachments/assets/fcc0db85-cdca-4e88-be62-900a318f4936

This only happens on TMDb helper... This is how it is on a different addon

https://github.com/user-attachments/assets/95f8808d-06e9-4179-8fdb-2f9b8110758d

### Expected Behavior

All details should remain after returning from info.

### Steps To Reproduce

Go to TMDB helper
Open the info page of any movie item
Browse through it
Return home

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Do you have progress indicators enabled in TMDbHelper? That will cause this issue due to a Kodi bug causing loss of information when they get set via JSON RPC.

I'm not really sure why you're reporting this as a skin issue though?

**Comment by Rinicko100** [comment]
> Do you have progress indicators enabled in TMDbHelper? That will cause this issue due to a Kodi bug causing loss of information when they get set via JSON RPC.
> 
I do have progress indicators turned on... there are 2 in the customise indicators settings... progress and progress percentage. I'm not sure which is causing it

> I'm not really sure why you're reporting this as a skin issue, though?
>
Ohh, apologies... I didn't really know what the cause of the issue was.

**Comment by jurialmunkey** [comment]
> I do have progress indicators turned on... there are 2 in the customise indicators settings... progress and progress percentage. I'm not sure which is causing it

No, not in the skin. It isn't a skin issue. It is in TMDbHelper settings under Trakt section.

This TMDbHelper setting will causes this issue due to a bug in Kodi JSON RPC method for setting progress back to file database.

![image](https://github.com/user-attachments/assets/7d09c638-cf51-4880-a519-2577723c114f)

**Comment by Rinicko100** [comment]
> > I do have progress indicators turned on... there are 2 in the customise indicators settings... progress and progress percentage. I'm not sure which is causing it
> 
> No, not in the skin. It isn't a skin issue. It is in TMDbHelper settings under Trakt section.
> 
> This setting causes this issue:
> 
> ![image](https://github.com/user-attachments/assets/7d09c638-cf51-4880-a519-2577723c114f)
> 

Ahh, I see... I did have that turned on. I'll go ahead and turn it off... Thanks for the info.

**Comment by jurialmunkey** [comment]
> Ahh, I see... I did have that turned on. I'll go ahead and turn it off... Thanks for the info.

FYI next version of TMDbHelper will remove the JSON RPC method which causes this bug as I don't think it is required anymore in Omega so this setting should work okay from then on.

Setting via JSON RPC was needed in Nexus but it *seems* to have been fixed/work in Omega without it. But we'll see... I'm sure I'll hear about it if it is still needed!
