### ISSUE TITLE
Getting a mix of old and new background startup images

### ISSUE THREAD

**Issue by matthius7** [jurialmunkey/skin.arctic.fuse.2#328]
### Skin section

Other

### Current Behavior

During startup I have hide widget initialization behind splash. I love the new background images but they are mixed in with the old AF images. Do I need to clear thumbnails to view only new ones..

### Expected Behavior

New background images

### Steps To Reproduce

Open Kodi,using latest Kodi and Google streamer. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
These are weather images. The only display if weather data has been fetched by whatever weather addon you're using.

**Comment by matthius7** [comment]
Ok makes sense was raining last night and images of rain in the background. Sorry for making a bug issue. It's very nice you incorporated this.

**Comment by Liquidrag** [comment]
> These are weather images. The only display if weather data has been fetched by whatever weather addon you're using.

I have Gismeteo installed but no weather images show, just a black screen with the AF2 logo and weather/temp. Is this correct? Is There an option to not have the black screen but the original backgrounds?

**Comment by matthius7** [comment]
> > These are weather images. The only display if weather data has been fetched by whatever weather addon you're using.
> 
> I have Gismeteo installed but no weather images show, just a black screen with the AF2 logo and weather/temp. Is this correct? Is There an option to not have the black screen but the original backgrounds?

I also use gismeteo and did nothing different setting up skin to make it happen.

**Comment by jurialmunkey** [comment]
> > These are weather images. The only display if weather data has been fetched by whatever weather addon you're using.
> 
> I have Gismeteo installed but no weather images show, just a black screen with the AF2 logo and weather/temp. Is this correct? Is There an option to not have the black screen but the original backgrounds?

For weather images check that you have the weather fanart multi pack installed. Can find a quick link to install it via the skin settings dependencies section. I'd thought I'd made it a forced dependency to install with the skin but realised I haven't.

For overriding the behaviour, you can set a folder of backgrounds for start up images in skin settings. If you set something other than default folder then it will not display weather fanart. So you could copy the launch folder from extras to somewhere outside the skin and then set that as your start up and it will never display weather.

**Comment by Liquidrag** [comment]
> For weather images check that you have the weather fanart multi pack installed. Can find a quick link to install it via the skin settings dependencies section. I'd thought I'd made it a forced dependency to install with the skin but realised I haven't.

Yea it wasn't a forced dependency, so I didn't have it. Now it shows. Speaking of dependencies, what does Arctic Waves do?

**Comment by jurialmunkey** [comment]
> > For weather images check that you have the weather fanart multi pack installed. Can find a quick link to install it via the skin settings dependencies section. I'd thought I'd made it a forced dependency to install with the skin but realised I haven't.
> 
> Yea it wasn't a forced dependency, so I didn't have it. Now it shows. Speaking of dependencies, what does Arctic Waves do?

It displays an animated wave background when content is loading in the media windows

**Comment by Liquidrag** [comment]
> It displays an animated wave background when content is loading in the media windows

Ok, I don't want that, Thnx for the info!
