### ISSUE TITLE
No easy way to get back to full screen live tv from guide window

### ISSUE THREAD

**Issue by Jimpan81** [jurialmunkey/skin.arctic.fuse.2#329]
### Skin section

PVR and Live TV

### Current Behavior

From live tv running , open guide window.
1 press back opens context menu
2 press back , takes med to home with live tv running in background

### Expected Behavior

Open guide , push back on remote for context menu and second press should take me to full screen live tv again

### Steps To Reproduce

From live tv running , open guide window.
1 press back opens context menu
2 press back , takes med to home with live tv running in background

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by booyakafoo** [comment]
What if you hold the back button?

**Comment by jurialmunkey** [comment]
This is not a bug. This is the same behaviour as in Estuary.

**Comment by jurialmunkey** [comment]
Actually maybe not. I'm getting weird inconsistent behaviour in Estuary where it sometimes goes home and sometimes goes straight back

**Comment by jurialmunkey** [comment]
Some weird behaviour with PreviousMenu action (which is what the ESC key does) not working properly

**Comment by Jimpan81** [comment]
Ok if not bug a bad choice . If you watch  live tv and open the guide , why would you like to end up on home ? 🤔 
Guide ->contex menu ->full screen live tv -> home  would be the natural way to handle this . 
This is how my current skin handle this

Please think this over again @jurialmunkey

**Comment by jurialmunkey** [comment]
I already fixed the issue. There is nothing to think over here. The fix is literally linked in the commit above your comment.

**Comment by Jimpan81** [comment]
@jurialmunkey sorry i missed that 🤦‍♂️.  Just tested , big thanks !
