### ISSUE TITLE
:bug: Auto Trailers on information screen very dark in background 

### ISSUE THREAD

**Issue by scoobyd00** [jurialmunkey/skin.arctic.fuse.2#33]
### Skin section

Video Info Dialog

### Current Behavior

When the auto trailer plays in the video information screen in the background, the video is very dark and is hard to see

### Expected Behavior

Video should be brighter and be seen

### Steps To Reproduce

Movie information view

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Resolved in https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/23
