### ISSUE TITLE
:bug: Adaptive dialog change in 2.3.2

### ISSUE THREAD

**Issue by L0bsang** [jurialmunkey/skin.arctic.fuse.2#331]
### Skin section

Widgets

### Current Behavior

The adaptive dialogs were looking different today after updating to the latest version (2.3.2). I thought they were not working, the dialog looked totally black. 

After looking closer it seems like just a darker effect applied, the dialog still changes colour slightly. Just wanted to confirm this change is intentional (no problem if it is). And whether the effect is still tied to Real Blur.

### Expected Behavior

Before:
![image](https://github.com/user-attachments/assets/3c5124a4-b0ef-467b-a3be-45fc2b9b1eea)
After:
![image](https://github.com/user-attachments/assets/7dd0325c-c621-4821-ac1c-b49198e8f496)

Side by side there is a clear difference.
I assume (perhaps incorrectly) that it is due to this commit: https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/8c0c7e839bcf4201198807ae3a6a18a99c816d59

So I played around with the 3 border styles (glass, dark glass, none). 
And while I saw the changes affect the infoline and options menu boxes, I didn't really see it affect the darkness of the dialog.

### Steps To Reproduce

1. Set an adaptive dialog background style. 
2. Open menu on a colourful item
3. Note muted colours in the dialog

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by L0bsang** [comment]
To re-iterate I have no problem if this is an intentional change, was just used to the more obvious colour change on adaptive dialogs. I can adjust to this darker menu.

**Comment by jurialmunkey** [comment]
No you're totally correct, I accidentally commented out the part of the code which makes the top foreground panel lighter than the background panel which holds the buttons.

The dark glass setting should make the overall dialogs darker by 30% but there should still be a differentiation between the top and bottom layer when that setting is not enabled.
