### ISSUE TITLE
:bug: Left side art blur color doesn't update when changing title art/backdrop

### ISSUE THREAD

**Issue by ghost** [jurialmunkey/skin.arctic.fuse.2#332]
### Skin section

Widgets

### Current Behavior

Right now, AF2 doesn't update the color of the blur on the left side of title art/backdrop (displayed when hovering over a title) to match newly applied title art

### Expected Behavior

AF2 should update the color of the blur on the left side of title art/backdrop (displayed when hovering over a title) to match newly applied title art

### Steps To Reproduce

1. Add a new movie or show
2. Add art/backdrop to it (through tinyMediaManager for example)
3. See that AF2 matches the left side blur color to the colors of the applied title art/backdrop
4. Change title art with new art/backdrop
5. Clear everything mentioned [here](https://github.com/jurialmunkey/skin.arctic.fuse/issues/838#issuecomment-2083920422) and refresh the title
6. See that AF2 hasn't updated the left side blur color to match the newly applied title art/backdrop and has kept the blur color of the old art/backdrop

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
If the new and old fanart have the same filename and path, then you'd need to delete the `blur_v2` folder too (in the same way as you do the `crop_v2` folder for the logos).

I do need to figure out a better way to force a refresh of these.

**Comment by ghost** [comment]
> If the new and old fanart have the same filename and path, then you'd need to delete the `blur_v2` folder too (in the same way as you do the `crop_v2` folder for the logos).

Did this and now the blur color updates. Thank you! :smile:
