### ISSUE TITLE
Video OSD movie/show synopsis shows then disappears 

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/skin.arctic.fuse.2#337]
### Skin section

Video Info Dialog

### Current Behavior

While the movie/show is playing, and you pull up a cast member movie/show, the synopsis shows then disappears in the flyout.

### Expected Behavior

While the movie/show is playing, and you pull up a cast member movie/show, the synopsis shows in the flyout. 

### Steps To Reproduce

1. Play movie
2. Go down to cast
3. Select a cast member
4. Click on a movie/show
5. Flyout window appears with synopsis then synopsis disappears. 

### Screenshots and Additional Info

https://github.com/user-attachments/assets/9ac1108a-9cc6-4358-b6c2-7b7d7bfe6e64

Probably linked to another bug you fixed for me here https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/131#issuecomment-2449054471

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
> Probably linked to another bug you fixed for me here https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/131#issuecomment-2449054471

Unrelated to that issue but I do know the cause. I saw the issue yesterday and will have a fix soon.
