### ISSUE TITLE
:bug: Fonts not compatible with Chinese characters.

### ISSUE THREAD

**Issue by yangyiminger** [jurialmunkey/skin.arctic.fuse.2#339]
### Skin section

Fonts and Languages

### Current Behavior

Sorry to bother u again, but the bug heavily affects my Kodi impression. After your previous upgrade to the font 'CJK', the version 0.02, it seems unfriendly to the Chinese characters (no matter simplified or traditional). There are so many common characters showing the abnormal squares, which has never happened in v0.01. So I guess the new font has compatibility with Chinese characters, like the image shows.
![screenshot_20241106194332](https://github.com/user-attachments/assets/67cf2a55-a9be-46fd-a8df-6c2b531da3fa)
![screenshot_20241106194133](https://github.com/user-attachments/assets/530bc230-0265-4824-8c70-5a0707e5be2f)

### Expected Behavior

I hope the issue can be fixed soon so I can get back to a perfect movie hub thanks to your contribution. Pity that I cannot help u on the codes.

### Steps To Reproduce

Just use the font 'CJK' v0.02 and the language 'Chinese' then the home page will show the unreadable codes.

### Screenshots and Additional Info

![screenshot_20241106194332](https://github.com/user-attachments/assets/67cf2a55-a9be-46fd-a8df-6c2b531da3fa)
![screenshot_20241106194133](https://github.com/user-attachments/assets/530bc230-0265-4824-8c70-5a0707e5be2f)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
There's not much I can do about this. Someone will need to make me a version of RobotoCondensed with the correct character sets and that still follows the metrics of the font correctly.

Otherwise I can only use fonts that are available.

**Comment by OfficerKD637** [comment]
@yangyiminger 
Have you tried Noto Sans and Noto Serif?
Go to the Google Fonts website: https://fonts.google.com/?query=chinese
And check if those support the missing glyphs/characters by using the 'type tester'

@jurialmunkey 
Hi Jurial!
Hope you're doing well!
Do you think the Noto fonts are a good fit for the skin (provided they support those missing characters)?

Also, would it be possible to have the Default font be automatically set depending on `System.Language`? 
Maybe something like `<include name="Default Font_Chinese" condition="String.Contains(System.Language,chinese)">`

Let me know what you think!

Thanks!

**Comment by jurialmunkey** [comment]
The font set is based upon noto already by combining with roboto. It must be combined with roboto to get correct spacing.

The issue is that true type has a upper glyph limit of  65,536 and the font already maxes this out. Kodi has no way to fill missing characters from supplementary fonts. 

That means no matter what font you use, you will always be missing characters as there are more than that many characters just in cjk languages alone (not to mention other languages using Cyrillic or Hebrew or Hindi or Arabic etc not being covered).

**Comment by OfficerKD637** [comment]
Yes I think I've heard about the upper limit of TTF fonts. 

But what about switching to OTF for CJK fonts? I think they can go higher than the 65000 limit?

EDIT: I was wrong haha. Although Kodi does support OTF files, to support more than 65,000 glyphs you'd need a OTC (OpenType Collection) file which would consist of multiple OTF files.

**Comment by flashlab** [comment]
Maybe this [post](https://blog.zzbd.org/kodi-ubuntu/#arctic-fuse-2-%E7%9A%AE%E8%82%A4) can help.

**Comment by jurialmunkey** [comment]
@yangyiminger Is the new "Default (Unicode)" font working well? It should have same coverage as Estuary as it merges the new default font Inter with the "Arial" font that comes with Kodi for unicode.

**Comment by iamxiaojianzheng** [comment]
> @yangyiminger Is the new "Default (Unicode)" font working well? It should have same coverage as Estuary as it merges the new default font Inter with the "Arial" font that comes with Kodi for unicode.

work nice
