### ISSUE TITLE
:bug: Episode Type does not display in the Plotbox

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse.2#359]
### Skin section

Library

### Current Behavior

I've noticed that using the latest versions of AF2 and TMDb Helper the episode type no longer appears in the Plotbox. I have an older setup (AF2 2.3.0 and TMDb Helper 5.3.0) and the episode type appears in that set up.

### Expected Behavior

Episode type appears as in previous versions

### Steps To Reproduce

go to TV Shows
selevct a show, and season

### Screenshots and Additional Info

![screenshot00001](https://github.com/user-attachments/assets/62c91be1-01c5-414c-b506-c96c239c0321)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Sorry I don't understand what you mean by "Episode Type" ?

**Comment by berkhornet** [comment]
Sorry, I meant "Series Premiere" etc. It used to show alongside the Episode Title in the Plotbox.

________________________________

**Comment by jurialmunkey** [comment]
> Sorry, I meant "Series Premiere" etc. It used to show alongside the Episode Title in the Plotbox.

Oh right! Very literally the "episode_type" infolabel. I was thinking of something completely different for some reason like "webisode" or "live" or something like that!

Fixed in TMDbHelper.

**Comment by berkhornet** [comment]
Many thanks!
