### ISSUE TITLE
Library Boxset Ratings Gone

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#360]
### Skin section

Widgets

### Current Behavior

Hey J,

50:50 if yo out this here or tmdbhelper....

All of a sudden library boxset ratings only now show kodi rating.

### Expected Behavior

Show all ratings as before 

### Steps To Reproduce

All api keys are fine and have not changed. 

### Screenshots and Additional Info

https://github.com/user-attachments/assets/a128cc2c-fa5e-4ad0-8ab3-b2c7d4343ad6

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Are you sure these ever had ratings? 

I can't think of how ratings for sets could even be retrieved. 

afaik OMDb, MDbList and Trakt don't have a content type for "sets" - they only have content types for individual movies - so there isn't even any data to retrieve from these services.

**Comment by jurialmunkey** [comment]
Are you sure you weren't using a combined view for sets before? Combined views will show the ratings because they are displaying the info for the item in the container, not the whole set.

![screenshot00883](https://github.com/user-attachments/assets/07f50f58-5b4b-43d3-94ba-a43dec2ff519)

**Comment by adamosborne83** [comment]
Maybe you're right.... 😉..... i tried to find an old video, and the best I could see was that box sets had kodi AND tmdb rating. So definitely had a minimum of 2 ratings. 

As you mentioned combined shows all.
