### ISSUE TITLE
:bug: Release data flickers, then disappears

### ISSUE THREAD

**Issue by jbelew** [jurialmunkey/skin.arctic.fuse.2#376]
### Skin section

Widgets

### Current Behavior

The release date in the Ratings Line flickers, then disappears with movie media items. I also noticed that it quickly switched from European style dates to US dates (my local settings), before no longer rendering. 

### Expected Behavior

Release date should appear in the Ratings Line. Appears to work correctly in Artic Fuse, assuming TMDB is providing this information.  

### Steps To Reproduce

1. Observe a movie widget in a non-Spotlight layout, or using Poster View in the Movie library, and navigate between movie media items. 

### Screenshots and Additional Info

Video can be provided if needed. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
TMDbHelper issue. ^^^ That should fix it.

**Comment by jbelew** [comment]
Thanks!

**Comment by jbelew** [comment]
Don't know if you'll see this comment or if I need to open a new defect, but I'm still getting a flicker. Specifically it flickers, about 100ms on my system, doing conversion between European style dates (dd-mm-yy) and my localized, en-us settings (mm/dd/yy).
