### ISSUE TITLE
:bug: Visual glitch on OSD seekbar when first displayed.

### ISSUE THREAD

**Issue by ChocOranger** [jurialmunkey/skin.arctic.fuse.2#385]
### Skin section

Video OSD

### Current Behavior

When starting a video the OSD seekbar initially shows a grey background stretching about 90% of the seekbar. After a few seconds (~5-30 depending on the video) it disappears.
![osd](https://github.com/user-attachments/assets/4769e9e5-ed1a-45ff-b228-0a2ffc87a63b)
![osd2](https://github.com/user-attachments/assets/d8cbc66e-31e6-4120-a94a-95e7dd0df12c)

### Expected Behavior

Either the grey extends all the way on the seekbar and stays or it doesn't appear at all.

### Steps To Reproduce

1. Start a video and bring up the OSD once playing.
2. Wait a few seconds and the grey background will disappear.

### Screenshots and Additional Info

Clean new install of the skin with no changes to test.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
The grey bar is the cache level progress.

It extended the full length is down to a weird bug in Kodi where it renders the full progressbar if the value is 0%

I think I can workaround it but we'll see if it causes other issues or not.
