### ISSUE TITLE
Up next shows up on movies

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#39]
### Skin section

Widgets

### Current Behavior

Never seen this before, but when I was on osd and scrolling to stop button, an Up Next movie was showing.

Never seen it before

### Expected Behavior

Not to show up 

### Steps To Reproduce

See pic 

### Screenshots and Additional Info

![20241008_203814](https://github.com/user-attachments/assets/81dd06eb-28d9-41a9-95c6-a7307f18072c)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by L0bsang** [comment]
From what I recall this happened in Fuse 1 as well. 

If you hover-over/move-cursor-to the next item button there is an overlay of the next item. 
For a movie there is no next item, it defaults to the current item. Nothing to do with the stop button.

**Comment by jurialmunkey** [comment]
L0bsang is correct. This was also the behaviour in AF1 and it isn't a bug.

If you're playing a tvshow, it shows the next episode after the current one. If you're playing a movie or are at the last episode of the show, then it displays a recommendation for what to watch next.

**Comment by adamosborne83** [comment]
> L0bsang is correct. This was also the behaviour in AF1 and it isn't a bug.
> 
> If you're playing a tvshow, it shows the next episode after the current one. If you're playing a movie or are at the last episode of the show, then it displays a recommendation for what to watch next.

Never ever seen this before 🤣 o well

**Comment by yuki-216** [comment]
I am equally confused by this. I know when it is playing a movie or are at the last episode of the show, and then it displays a recommendation for what to watch next. However, I mainly watch content from my local media library, and I wish there were an option to change the recommendation to the next video from my local media library, instead of the current forced recommendation for online videos, which is not user-friendly
