### ISSUE TITLE
 viewtype screenshots dont show while region is Arabic in hubs 

### ISSUE THREAD

**Issue by taiseer999** [jurialmunkey/skin.arctic.fuse.2#398]
### Skin section

Widgets

### Current Behavior

Hi Juiral,
 
Viewtypes screenshots do not pop up in the "hub" widget style selection but they do in the configure viewtypes in skin setting.(Widgets_Preview).  if region is Arabic.  

### Expected Behavior

to show the screenshots 

### Steps To Reproduce

edit the widget viewtype, a window should pop up to show the example of the types. 

### Screenshots and Additional Info

Arabic - widget type 
![Screenshot 2024-11-21 at 11 42 39 AM](https://github.com/user-attachments/assets/9688e0ab-99a1-4b48-a50b-db6ee3338d11)

English - widget type 
![Screenshot 2024-11-21 at 11 41 40 AM](https://github.com/user-attachments/assets/dd54cb72-76a3-4a7c-b3d9-b4cb270dd072)

Arabic - Viewtypes in Skin Settings
![Screenshot 2024-11-21 at 12 06 05 PM](https://github.com/user-attachments/assets/56c816b7-c42e-476f-9638-fca86f4304eb)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by taiseer999** [comment]
THis is a fresh copy of the Skin on new Kodi install

![Screenshot 2024-11-21 at 12 18 19 PM](https://github.com/user-attachments/assets/de6b2e1c-35d5-43d1-a289-153df1932b12)

**Comment by jurialmunkey** [comment]
I'm not sure if there's anything the skin can do.

The skin is doing a `String.IsEqual(Container(3).ListItem.Label,$LOCALIZE[ID])` to check the label against the localization to determine what image to display and for some reason Kodi is returning false for RTL languages.

The only "solution" would be to remove the localization of these labels, which doesn't seem like much of a solution really.

There's no way to attach additional properties to the select dialog to give a fixed value to compare against while still keeping the localized labels.

**Comment by taiseer999** [comment]
Removing the localization of these labels did not do the trick
![Screenshot 2024-11-22 at 6 50 34 AM](https://github.com/user-attachments/assets/156158e1-a96f-4332-bcd0-722e7ff0f1c2)

**Comment by taiseer999** [comment]
The strange thing is its working everywhere else
![Screenshot 2024-11-22 at 7 16 32 AM](https://github.com/user-attachments/assets/045aaa39-da28-4914-8e49-85b2dbfb3e9c)

**Comment by jurialmunkey** [comment]
The view types are scripted via skinvariables so the image is attached internally via the script in the custom vietype dialog.

The style select just uses the default kodi select dialog

**Comment by taiseer999** [comment]
its a dead end then, thanks..

**Comment by jurialmunkey** [comment]
I figured out the issue. There was a missing localization for the header "Style" and so that's what's causing the mismatch. I realised after looking at your screenshots that the "preview" button was missing and also the header wasn't translated.

**Comment by taiseer999** [comment]
thank you its working
