### ISSUE TITLE
Not Able To Define Custom Submenu 

### ISSUE THREAD

**Issue by BigRedJim** [jurialmunkey/skin.arctic.fuse.2#4]
### Skin section

Widgets

### Current Behavior

First of all, I LOVE Fuse 2. It's so clean. Amazing work again.

When setting a widget as a Custom Submenu you cannot set the content as the options do not appear to select from. Therefore the widget doesn't appear.

### Expected Behavior

To be able to select what you want for the submenu.

### Steps To Reproduce

Set "Custom Submenu" as widget type, on the right the options do not appear to select from.

### Screenshots and Additional Info

![Screenshot_20241006-134207](https://github.com/user-attachments/assets/23a1f650-f904-4cd5-b528-d9d5db16504f)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah, I accidentally copied in the wrong visibility condition. Easy fix!

**Comment by BigRedJim** [comment]
Great, thanks,
