### ISSUE TITLE
Video OSD: Suggest a sequel to the film

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse.2#415]
### Skin section

Video OSD

### Current Behavior

When you play Sonic 1, and you press the "next" button, it is not Sonic 2 that is offered, but Sonic 3. This problem also occurs on other sagas.

![image](https://github.com/user-attachments/assets/6fa7b07e-3d8b-47f9-981c-cc7910b4b014)

### Expected Behavior

Suggest the sequel.

### Steps To Reproduce

...

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is the next movie recommended on TMDB. If you want to play a play list then play a play list and it will show the next item in the playlist. Otherwise it is the next recommended movie from tmdb which I cannot control

**Comment by Bindou01** [comment]
Okay, I understand better. Too bad TMDB makes inconsistent suggestions. This button suggests that it would be the logical continuation of what is currently being viewed. And I suppose Kodi is not able to handle that either?

**Comment by jurialmunkey** [comment]
The button shows the next item in the playlist.

If your playlist is empty it shows a recommendation from tmdb.

If you want to play a collection of movie then you should play them as a playlist and it will show the next item
