### ISSUE TITLE
Actors Info Sheet: Show English description when preferred language description is missing

### ISSUE THREAD

**Issue by Bindou01** [jurialmunkey/skin.arctic.fuse.2#420]
### Skin section

Other

### Current Behavior

When there is no description in the preferred language, the information sheet does not return any information, even when there is an English description on TMDB.

![image](https://github.com/user-attachments/assets/79cf0479-a92c-4088-bc87-036b2e70c269)

### Expected Behavior

Show English description when French description is unavailable.

But I don't know if this is caused by Kodi, Scrapper or Fuse 2.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Nothing to do with the skin.

Tmdb api does not support fallback language.

https://www.themoviedb.org/talk/5abe2eff0e0a264a5a00d324

https://trello.com/c/UV1IGYfN/3-add-support-to-fallback-translation-queries
