### ISSUE TITLE
Finale and Premiere indicators not well aligned with rounded corners

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#422]
### Skin section

Widgets

### Current Behavior

Hello Jurial,

Really loving the look of the rounded corners, throughout the skin... gives it a very friendly and visually appealing appearance.

One small issue, though. It seems the premiere  and finale indicators haven't followed suite and are not properly aligned on top of the landscape artwork... Shown in images below

![Kodi_20241126_024127](https://github.com/user-attachments/assets/97b20b7f-e9c8-408e-ab4e-2f45d3c26245)
![Kodi_20241126_023604](https://github.com/user-attachments/assets/f1e87492-e761-4649-b776-61d2559773b4)
![Kodi_20241126_021636](https://github.com/user-attachments/assets/ccd5257a-a0e0-43a8-9eaf-8d845fc99961)

It's one of those, once you see it, you can't unsee it situations

### Expected Behavior

It should be aligned at the top without parts of the widget showing above it.

### Steps To Reproduce

Switch on the indicators in details settings 
Go to the first episode of a tv show season in calendar or in addon
View the top

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Knew there were going to be a couple of spots I missed updating border attributes. Easy fix.

**Comment by Rinicko100** [comment]
> Knew there were going to be a couple of spots I missed updating border attributes. Easy fix.

Nice nice nice... I'll let you know if I spot any other ones. Thank you 🙏🙏
