### ISSUE TITLE
context menu width

### ISSUE THREAD

**Issue by C-O-D** [jurialmunkey/skin.arctic.fuse.2#426]
### Skin section

Other

### Current Behavior

Wouldn't necessarily call it a bug nor a feature request but the context menu has recently been shortened in width. About 75% of my entries are now cut off on the right. I think I'd like it better if it were wider again, as I don't think the width bothers me because the focus is on the context menu itself at the moment of use anyway and it disappears again as soon as you have made a selection.

### Expected Behavior

A wider context menu so that more items are readable

### Steps To Reproduce

Use the context menu anywhere

### Screenshots and Additional Info

![screenshot00032](https://github.com/user-attachments/assets/ec1339cd-a2d7-4939-a0ad-04b2759fd4dc)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I guess this comes down to font + language because with default font in English I've got plenty of space. But, no big deal to widen.

**Comment by C-O-D** [comment]
Thanks a lot 🙏

**Comment by Beats24-7** [comment]
Yes, it only has become an issue in some places (settings, OSD, etc.) since the font of the skin has been changed. It was looking fine before. But the new font looks better so maybe a change of the width of some menus will help.
