### ISSUE TITLE
Rounded corners on Dialog boxes not aligned

### ISSUE THREAD

**Issue by berkhornet** [jurialmunkey/skin.arctic.fuse.2#429]
### Skin section

Other

### Current Behavior

I noticed that on some dialog boxes the corners are not correctly aligned, with a lighter colour showing through

### Expected Behavior

Correctly aligned corners

### Steps To Reproduce

See screenshots

### Screenshots and Additional Info

![screenshot00000](https://github.com/user-attachments/assets/206d30d0-3ff0-465a-8c4c-50f8ac4166e9)
![screenshot00001](https://github.com/user-attachments/assets/32b92278-4cfe-4882-b6e7-730d01e5044b)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I cant reproduce. Are you using an unmodified version of the skin? It looks like you have old diffuse textures.

**Comment by jurialmunkey** [comment]
Oh wait. Is this with Adaptive disabled?

**Comment by berkhornet** [comment]
Yes, adaptive was disabled. All looks good now. Thank you.
