### ISSUE TITLE
🐛  Collections missing from Info page

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#43]
### Skin section

Widgets

### Current Behavior

Collections is usually somewhere in info page,  it shows other parts of a movie or franchise, but I can't seem to find it anywhere at the moment

### Expected Behavior

Collections should be one of the items on the info page

### Steps To Reproduce

1) Find a movie that has multiple parts
2) Open the info page for it

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This was added in https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/422e89b601a3240e5a1a424508bcc621d90b261d
