### ISSUE TITLE
:bug: Problem with the separator string in movie revenue info

### ISSUE THREAD

**Issue by Lam4hound** [jurialmunkey/skin.arctic.fuse.2#449]
### Skin section

Video Info Dialog

### Current Behavior

Currently the skin uses string id "19107" from the kodi language file as as separator in the revenue label in the movie info dialog. This is meant for labels that deal with the time of the day.

#. part of timer information text (e.g. "Next recording on 10/10/2016 at 9:00 AM")
#: xbmc/pvr/guilib/guiinfo/PVRGUITimerInfo.cpp
#: xbmc/pvr/timers/PVRTimerInfoTag.cpp
msgctxt "#19107"
msgid "at"
msgstr "klo"

The Finnish translation for this string is "klo", which is short for "clock" and it doesn't make sense when it is used when dealing with monetary values.

### Expected Behavior

I'd like to suggest to create a new translatable string in the skin language file so that the text can be changed to something more sensible. I would probably translate it to just "/" as there are no prepositions in Finnish language. I believe that other languages would also benefit from this change.

### Steps To Reproduce

Select a movie from your library -> Press "I" -> Look at the revenue / budget values

### Screenshots and Additional Info

![screenshot00011](https://github.com/user-attachments/assets/143240f3-b8d4-44c9-a3dc-2a52e259b610)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It doesn't use 19107, it uses 19159 which is "from" - as in "the movie made $X from $Y budget".
But I take your point. Easy enough to provide a separate localization label.
