### ISSUE TITLE
:bug: Aerial screensaver not working anymore since version v2.4.33

### ISSUE THREAD

**Issue by pimw1** [jurialmunkey/skin.arctic.fuse.2#461]
### Skin section

Other

### Current Behavior

When the screensaver should kick in, it shows it for 1 milisecond, after which the screen goes to black. When pressing a random button, the regular user interface is visible again. This happens since version v2.4.33 or v2.4.32 .

The default Asteroids screensaver is working fine.

### Expected Behavior

When the screensaver should kick in, it should show the screensaver.

### Steps To Reproduce

1. Install the Aerial screensaver
2. Go to Settings -> Interface -> Screensaver
3. Set Screensaver mode to "Aerial"
4. Click on "Preview"

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Works fine for me.

**Comment by pimw1** [comment]
Autoplaying trailers is disabled.

I've found the setting that is causing the issue: 

- when "Background video"  is disabled, the screensaver is going to a full black screen.
- when "Background video" is enabled, the screensaver is working normally

**Comment by jurialmunkey** [comment]
Long standing Kodi issue with foreground video in that case. Some systems just cannot display video properly when there is a foregrounded dialog with a video window. Might have to add a warning to that option that it can be an issue on some systems.
