### ISSUE TITLE
:bug: Suboptimal fallback image used for Discart in Disc and Circle widget style

### ISSUE THREAD

**Issue by metaltermite** [jurialmunkey/skin.arctic.fuse.2#462]
### Skin section

Widgets

### Current Behavior

`Disc` and `Circle` widget styles use `Discart` images. When an item's `Discart` is unavailable the fallback image is the items `Thumbnail`. Thumbnail images are often unrecognizable as a means to identify content.

### Expected Behavior

If possible can a hierarchy of fallback images be implemented, such as `Poster`, `Keyart`, `Landscape`, etc. This assures recognizable art is used as a fallback image.

Apologies in advance if this isn't possible on Kodi. I am not familiar with the limitations and capabilities of skins.

### Steps To Reproduce

1. Create a widget referencing obscure movies in your library
2. Set the widget style as `Circle` or `Disc`
3. There's a good chance some of your items will lack `Discart` and use the `Thumbnail` as a fallback image.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is not a bug. It is intentional so that episodes / albums / artists / songs will display correct artwork as these will preference thumbnail for cover artwork or episode details.

Bug reports should only be used to report issues where the skin is not working correctly, not for requesting changes in functionality. In future, please use the feature requests feature section to request new functionality.

I do see benefit in the feature request but please make sure to use the correct section in future.

**Comment by jurialmunkey** [comment]
Need to undo this change. It causes problems for other content types.
https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/469

**Comment by Bindou01** [comment]
This change made over a few days was extremely interesting. It would be a great idea to see it arrive soon. 
@jurialmunkey, should we recreate a request in the discussion section?

**Comment by jurialmunkey** [comment]
No it will not be implemented due to the issues it causes

**Comment by Bindou01** [comment]
Thanks for the info.
In use cases similar to mine, this didn't pose any particular problem. Maybe you could one day offer it as an option by warning of potential problems, in an Experimental Features section.

Have a nice day.

**Comment by metaltermite** [comment]
> No it will not be implemented due to the issues it causes

Thanks for giving it a shot. Appreciate the effort and time 👍 It looked cool while it lasted (about 25% of my movie library doesn't have discart).

**Comment by Bindou01** [comment]
@OfficerKD637 
Do you have any idea how we could solve this problem? I was thinking of a new "Disc 2" Widget that would favor the fallback on the poster rather than the Fanart.
