### ISSUE TITLE
Youtube nag screen does not allow either selection.

### ISSUE THREAD

**Issue by mattm382** [jurialmunkey/skin.arctic.fuse.2#463]
### Skin section

Other

### Current Behavior

On a new installation of the skin, with trailers to play automatically on Information screen, there is a nag screen that pops up if you have not installed Youtube yet. Neither choice is selectable. You need to back out to the Kodi Add-on repo and install it from there.

I apologize if this is not a skin issue, but rather a Youtube add-on issue. If I navigate to the Information screen in Estuary and then press the Trailer button, I am given the choice to choose to install, and they are selectable. I understand that's not quite the same thing as the trailers playing automatically once landed on the information screen, so I cannot exactly test for the expected outcome in Estuary.

### Expected Behavior

When prompted that Youtube is required for the trailer feature, Youtube will be installed if Yes is selected.

### Steps To Reproduce

- New install of AF2.
- Enable auto trailers for Information screen.
- Initiate Information screen
- You will see neither button is selectable.

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Sorry im not supporting bugs with the auto trailer functionality. It has a big warning stating that it will cause issues and not to report them if it is enabled.

**Comment by mattm382** [comment]
> Sorry im not supporting bugs with the auto trailer functionality. It has a big warning stating that it will cause issues and not to report them if it is enabled.

The warning is for when you have them playing automatically inside widgets. I'm talking about when you purposefully activate the Information screen. I did not know that was also problematic.

**Comment by jurialmunkey** [comment]
I thought it was enough to have the warning on the main option and not need to put it on every possible one but obviously it's not clear enough. I've now put it on every option. 

If you autoplay things it will cause problems because of how kodi refreshes widgets when playback starts and stops.
