### ISSUE TITLE
Kodi crashing, when bringing up context menu, to remove things from trakt watchlist, log included.

### ISSUE THREAD

**Issue by JFG1000** [jurialmunkey/skin.arctic.fuse.2#472]
### Skin section

Widgets

### Current Behavior

Hi jurial this may sound crazy, but something is causing kodi to completely crash when using fuse 2, with Fen light, when i bring up the context menu from my home screen but holding over a widget, when i select trakt lists manager, remove from trakt watchlist, kodi completely crashes, also If i go into the addon itself, go to tools, clear all cache, it also crashes kodi, i changed skin to estuary and repeated these same steps and the issue does not happen, only seems to be when fuse 2 is applied, I've attached a log

UPDATE : I switched TMDB helper versions to the official kodi one and the issue completely goes away, so I'm not sure if it's a most recent update to the helper that's causing it. 

1st log for the trakt list manager

https://paste.kodi.tv/iwupahijuf

Second log clear all cache within fen light, which also brings up a dialog box 

https://paste.kodi.tv/apufavugik

If you could please take a look at this it would be greatly appreciated. 

### Expected Behavior

Context menu box usually let's is navigate when using trakt lists manager, and clear cache within the addo. 

### Steps To Reproduce

Ok widget home screen press and hold over widget, trakt lists manager, remove from watch list.

Within addon - tools, clear all cache

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Not a skin issue.

Addon probably uses some weird non-native scripted dialog and Kodi's GUI Window API doesn't know how to deal with it properly when accessing its properties. Couple of possible workarounds to this method.

Please try using latest version of script.module.jurialmunkey (v0.2.5) with latest TMDbHelper. Not certain if this update will or won't workaround the underlying Kodi problem since I don't use this addon and can't recreate this problem using official addons; but if it doesn't work, there's another "safer" approach I can try.

**Comment by JFG1000** [comment]
Ok i can try but where do i find the latest version of script module? Just checked for updates and nothing is Available

**Comment by JFG1000** [comment]
Just checked I'm on the latest version already, seems to be ok now thankyou very much

**Comment by jurialmunkey** [comment]
Okay great! Let me know if it does start happening again but hopefully this is enough to workaround the problem.

**Comment by JFG1000** [comment]
I will do! Thankyou for all of your work!

**Comment by JFG1000** [comment]
@jurialmunkey can i just ask when the 0.25 update was pushed? As I don't even remember updating it

**Comment by jurialmunkey** [comment]
> @jurialmunkey can i just ask when the 0.25 update was pushed? As I don't even remember updating it

I pushed it when I made the comment saying to try it. It would've auto-updated from my repo.
