### ISSUE TITLE
2.50 update cannot move to combined menu

### ISSUE THREAD

**Issue by derrgoo** [jurialmunkey/skin.arctic.fuse.2#476]
### Skin section

Widgets

### Current Behavior

When my widgets are combined I am no longer able to go down to change categories. 

### Expected Behavior

Move down and select category when widget combined

### Steps To Reproduce

1. Combine widgets 2. Load desired category 3. Try to goto menu at bottom. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by Bindou01** [comment]
It seems to me that the problem is not solved.
