### ISSUE TITLE
Down Bump

### ISSUE THREAD

**Issue by adamosborne83** [jurialmunkey/skin.arctic.fuse.2#478]
### Skin section

Widgets

### Current Behavior

Don't really know if it's a bug or not, but the down bump suddenly seems really over exaggerated. 

### Expected Behavior

Little bump

### Steps To Reproduce

See video

### Screenshots and Additional Info

https://github.com/user-attachments/assets/3f59f77c-017f-410a-b239-2aa2c6a5aa91

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Side effect of the shorter widget styles. Impossible to fix better than it is due to the hack used. Either this or no text widget.

**Comment by adamosborne83** [comment]
> Side effect of the shorter widget styles. Impossible to fix better than it is due to the hack used. Either this or no text widget. 

Love the text widget, so compromise it is.
Thank you.

**Comment by jurialmunkey** [comment]
I ended up having to remove that hack anyway as it caused other issues. Now downside is that the shorter widgets won't adjust the gap to next widget in detailed/advanced styles (but still will in basic)

**Comment by adamosborne83** [comment]
> I ended up having to remove that hack anyway as it caused other issues. Now downside is that the shorter widgets won't adjust the gap to next widget in detailed/advanced styles (but still will in basic)

Yea, i did read this morning about other issues, and I saw one of your commits removing the spacing.

I'll see it later, but it is what it is.

Thanks again, J.
