### ISSUE TITLE
Navigating the home menus is wierd.

### ISSUE THREAD

**Issue by Goldenfreddy0703** [jurialmunkey/skin.arctic.fuse.2#480]
### Skin section

Widgets

### Current Behavior

Hey so I thought somebody else would make a bug report this afternoon and I didn't want to write a whole paragraph over this bug report but here I am lol.

Ok so when using a remote or keyboard to navigate in the main home menus, they automatically either bump or pull up the menu or favorites or options depending on what you set your home > Action (Left/Up) 

### Expected Behavior

To not automatically open these random windows.

### Steps To Reproduce

1. Just set up some main menus and maybe items and navigate through them and you will see what I'm talking about. 

### Screenshots and Additional Info

I hope you were able to reproduce this bug, the device I'm using as we speak is an android TV device. 

Edit: forgot to say that I'm using the Advanced(Widgets + Information + More) mode to help reproduce this issue. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I am not able to reproduce this behaviour.

**Comment by Goldenfreddy0703** [comment]
Let me try to reproduce it again but on my PC this time. When the skin updated a few hours ago, this is when I started getting this issue.

**Comment by Goldenfreddy0703** [comment]
https://github.com/user-attachments/assets/aa8be77e-0d17-4013-add9-aabf7f2ecf6b

Ok so i was able to reproduce it on my pc so when navigating through these menus, its pulling up the menu and it looks like its utilizing the actions when you have the home > Action (Left/Up) set to something. 

![image](https://github.com/user-attachments/assets/435287f6-652f-4296-8cf0-e248d2eff45d)
Another user on discord had the same issue as well when moving between the hubs and all.

**Comment by jurialmunkey** [comment]
No widgets set.

**Comment by jurialmunkey** [comment]
I knew I would regret implementing smaller sized widgets...

**Comment by Goldenfreddy0703** [comment]
ohhhhhh that could explain alot, I have no widgets really set except my addons cause i mostly liked the spotlights so that the skin can load faster for android tv's and stuff. Thank you for telling me about the widget portion of the skin, I had a widget for Discover and i was too dumb to realize why my discover hub didn't do this. 

Again Thank you

**Comment by jurialmunkey** [comment]
Now I wait for people to complain about how the last widget will be positioned weirdly if they use the shorter style. Probably should just rip it out entirely again -- thought I had it working nicely but alas not to be.

**Comment by Goldenfreddy0703** [comment]
To be honest, you did have it working nicely, it was probably just a small bug with either navigation or button positioning or other factors. I do really like this skin and its been amazing using this skin. 

Oh for example, if the user had 4 tiles set when customizing options and the user navigates those 4 tiles, sometime navigation can be weird. 

https://github.com/user-attachments/assets/b17885a2-bc47-4038-a346-0fdcb05bca10
If you like i can make a bug report on that.

**Comment by jurialmunkey** [comment]
> If you like i can make a bug report on that.

Yes please. Dont have time to look at it fixing it properly right now but I know what the general cause will be. 

Don't need a detailed report basically just the comment with the video -- it's just so I don't forget.
