### ISSUE TITLE
Hide widget initialisation behind splash not working

### ISSUE THREAD

**Issue by xgrbk** [jurialmunkey/skin.arctic.fuse.2#483]
### Skin section

Other

### Current Behavior

Even though the "Hide widget initialization behind splash" option is checked in Arctic Fuse 2, the application bypasses the splash screen and goes straight to the home hub. In this state, the widgets continue to load visibly on the home screen, which defeats the purpose of the splash screen setting.

### Expected Behavior

The splash screen should remain visible until all widgets are fully initialized, ensuring a seamless transition to the home hub.

### Steps To Reproduce

Open the Arctic Fuse 2 settings.

Enable the "Hide widget initialization behind splash" option.

Restart the application.

Observe the behavior during startup.

### Screenshots and Additional Info

Version of Arctic Fuse 2 being used: v2.5.2
Device used: Chromecast with google tv

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Works fine for me.

Note that it only checks the first widget to see if that has loaded. If your first widget is disabled, has no items, or has loaded then the splash will stop.

**Comment by xgrbk** [comment]
> Note that it only checks the first widget to see if that has loaded. If your first widget is disabled, has no items, or has loaded then the splash will stop.

Thanks for pointing this out. I have my home hub movie hub and tv hub as categories all within my home hub (Am I saying this right? lol) and home hub was first category with no items in it.
