### ISSUE TITLE
resource.language.ar_sa is not in root

### ISSUE THREAD

**Issue by taiseer999** [jurialmunkey/skin.arctic.fuse.2#50]
### Skin section

Other

### Current Behavior

Arabic language folder is enclosed in the English folder thus Arabic language wont display
![Screenshot 2024-10-09 at 10 37 02 AM](https://github.com/user-attachments/assets/f878eef1-1ef2-4191-9d59-ebaea047133f)
. 

### Expected Behavior

To relocate folder to root of language Folder

### Steps To Reproduce

Language remains default

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ah this was from your PR here: https://github.com/jurialmunkey/skin.arctic.fuse.2/pull/2/files

I didn't spot that it was in the wrong folder before I merged it. Should be fixed now.
