### ISSUE TITLE
Custom window background color changes back after reboot. 

### ISSUE THREAD

**Issue by matthius7** [jurialmunkey/skin.arctic.fuse.2#54]
### Skin section

Other

### Current Behavior

Set the custom highlight colors to whatever I like. For instance green is what I choose. Reboot system or Kodi and it reverts back to purple. 

### Expected Behavior

Stays green after reboot. 

### Steps To Reproduce

Settings,skin settings,appearance,custom window background. 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by matthius7** [comment]
Using hub 1101 I indeed was able to see all ratings and create a spotlight widget. You are a master at your craft sir. The godfather of skinning. Absolutely amazing work in all ways. Thank you for your guidance last week. Uninstalled AF after I set this one up. Its much faster on my g-streamer than the original Af.  Slimmed way down.

**Comment by JFG1000** [comment]
> Using hub 1101 I indeed was able to see all ratings and create a spotlight widget. You are a master at your craft sir. The godfather of skinning. Absolutely amazing work in all ways. Thank you for your guidance last week. Uninstalled AF after I set this one up. Its much faster on my g-streamer than the original Af. Slimmed way down.

I'm also now experiencing no display of my splash screen, would you know how i could possibly fix it?

**Comment by jurialmunkey** [comment]
I think this is the same issue as https://github.com/jurialmunkey/skin.arctic.fuse.2/issues/116

If so it is resolved by https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/e939b567d4839d8799a0cbe049a663b8bff70790 which will be in next update.
