### ISSUE TITLE
🐛 "Returning TBC" not showing on returning tv shows when detailed is selected 

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#55]
### Skin section

Widgets

### Current Behavior

When "TV Shows Detailed" is selected in the "Details" section under "Status", it doesn't show "Returning TBC" which would normally inform that the returning date hasn't been confirmed... Instead it shows Returning and an incorrect date
![Kodi_20241009_054402](https://github.com/user-attachments/assets/f3c3f54e-5175-4438-9dd0-ec0ef0eb9395)

### Expected Behavior

It should show "Returning TBC" on dates that haven't been confirmed... It was like this on AF1

### Steps To Reproduce

Select TV shows: Detailed, under the Details section in skin settings 

Navigate to a TV Show that is returning but date hasn't been confirmed 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is intended. There were too many different opinions on what should be shown. So, to keep it simple, I show the available date for detailed (next if available, otherwise last), or no date for basic.

**Comment by Rinicko100** [comment]
> This is intended. There were too many different opinions on what should be shown. So, to keep it simple, I show the available date for detailed (next if available, otherwise last), or no date for basic.

It's just that last is already in the infoline so it becomes double info... it's also a bit misleading at first to see a returning date only for it to be the last aired date... I think TBC was the better option

Just noticed last is different from what is in infoline... infoline is first aired... I still think TBC is better information that the date it last aired though as that can be seen by checking the last episode date

**Comment by jurialmunkey** [comment]
The argument for showing last was for episodes so you can quickly compare episode date against last aired date and know whether or not it is the last episode that has aired and/or how close you are to the last episode. 

Like I said, too many opinions about what is "right" or "better" so I've just chosen to show the date.

**Comment by Rinicko100** [comment]
> The argument for showing last was for episodes so you can quickly compare episode date against last aired date and know whether or not it is the last episode that has aired.
> 
I thought when the last episode aired, it'll switch from "Airing" to "Returning" or "Aired"

> Like I said, too many opinions about what is "right" or "better" so I've just chosen to show the date. 
>
It's no problem, though, I'll have to get used to this one... I'm just bad at reading dates at a glance, which is why I prefer the TBC, so I don't think a return date has been announced when it hasn't.

**Comment by Rinicko100** [comment]
> > The argument for showing last was for episodes so you can quickly compare episode date against last aired date and know whether or not it is the last episode that has aired.
> > 
> I thought when the last episode aired, it'll switch from "Airing" to "Returning" or "Aired"
> 
> > Like I said, too many opinions about what is "right" or "better" so I've just chosen to show the date. 
> >
> It's no problem, though, I'll have to get used to this one... I'm just bad at reading dates at a glance, which is why I prefer the TBC, so I don't think a return date has been announced when it hasn't.
> 
>

**Comment by jurialmunkey** [comment]
> I thought when the last episode aired, it'll switch from "Airing" to "Returning" or "Aired"

Yes, perhaps it could have a better label if the date is in the past.

TMDb just uses "Returning" for any show that isn't officially cancelled/ended. Unfortunately it doesn't really have a way to differentiate between a show which is officially renewed, and one that simply hasn't been officially cancelled yet (e.g. see The Orville).

**Comment by Rinicko100** [comment]
> > I thought when the last episode aired, it'll switch from "Airing" to "Returning" or "Aired"
> 
> Yes, perhaps it could have a better label if the date is in the past.
> 
> TMDb just uses "Returning" for any show that isn't officially cancelled/ended. Unfortunately it doesn't really have a way to differentiate between a show which is officially renewed, and one that simply hasn't been officially cancelled yet (e.g. see The Orville).

I see... I didn't realize it was from tmdb, I thought it was directly from the skin.

Great addition with that recent comit... Last aired label for no official return date.. That makes it easier to differentiate

**Comment by Rinicko100** [comment]
Just seen this in the new update [#](https://github.com/jurialmunkey/skin.arctic.fuse.2/commit/3db9a08f29c01766de87ef566d72460e665e8a1d)

It's the perfect compromise to get both sides... thank you very much
