### ISSUE TITLE
:bug: If the first side menu widget has no content, widgets cannot be accessed from their corresponding side menu category.

### ISSUE THREAD

**Issue by SK4G** [jurialmunkey/skin.arctic.fuse.2#62]
### Skin section

Widgets

### Current Behavior

If the first side menu widget has no content, widgets cannot be accessed from their corresponding side menu category, even if other widgets in the same category have content. The widgets can only be accessed by navigating to a side menu category where the first menu item has content, then scrolling vertically to access the stacked widgets from the category with inaccessible widgets. 

### Expected Behavior

Widgets can be accessed from their corresponding side menu category.

### Steps To Reproduce

1. Create widget in the first position which may not have content at all times such as `special://skin/extras/playlists/InProgressMovies.xsp` 
2. Create second widget in same side menu category such as `special://skin/extras/playlists/TopRatedMovies.xsp`
3. Try to access widgets in this side menu category from the side menu

### Screenshots and Additional Info

The current default Movies side menu category has default side menu widgets which lead to this behavior. The first item is `special://skin/extras/playlists/InProgressMovies.xsp`
This bug is also present in AF1.

```
2024-10-10 09:01:42.718 T:18090   error <general>: Control 101601 in window 10000 has been asked to focus, but it can't
2024-10-10 09:01:53.417 T:18090    info <general>: Skipped 9 duplicate messages..
2024-10-10 09:01:53.417 T:18090   error <general>: Control 101601 in window 10000 has been asked to focus, but it can't
```

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
This is likely unfixable.

**Comment by ds2288** [comment]
This drives me nuts. Love the skin but I want my Next Episode widget up top. Once I’ve watched everything, this bug rears it’s head. I have no idea about programming but can’t say I’ve ever come across the issue with other skins utilising the same layout. It would just shoot across from the menu items to the next widget which becomes the first widget. If it’s unfixable, its unusable in a Netflix style setup.

**Comment by jurialmunkey** [comment]
Oh well that sucks for you.

There are plenty of ways around the issue like simply reordering your widgets so it isn't the first one or using skin variables to assign a fall back widget if the primary one is empty.

**Comment by ds2288** [comment]
> Oh well that sucks for you.
> 
> There are plenty of ways around the issue like simply reordering your widgets so it isn't the first one or using skin variables to assign a fall back widget if the primary one is empty.

Didn’t know about the fallback widget. That should work. No real need for the first part of the reply. Seems to be a thing with developers, can’t take criticism.

**Comment by jurialmunkey** [comment]
Could say the same about the first part of your original comment. Completely unnecessary.

Youre not providing criticism, youre just complaining about a technical limitation which I already mentioned is likely not possible for the skin to work around whilst retaining its feature set. 

You haven't seen the issue in other skins because other skins do not offer these same features or depth of customisation. I would have to cut certain features for it to work as you say and then you'd be in here complaining about the cut feature. 

Its the attitude of entitlement that I take issue with. I've been doing this for more than a decade. I know what I'm talking about and very very aware of what the skin engines limitations and abilities are and yet people with no knowledge or experience still feel the need to constantly challenge me on it and act entitled despite me giving up so much of my free time.

Youre acting like I'm a company selling a product, not a hobbyist passionate about sharing my work.

**Comment by ds2288** [comment]
Not really. Just stated the facts. I never said the skin was flawed or had anything wrong with it. I just confirmed the behavior and stated it won’t work in the classic streamer style of having Next episodes up top. Yes, that drives me nuts but I’m not going to ditch it. Never said your work wasn’t appreciated or impressive. If you don’t want issues to be raised or take comments too personally, don’t provide a medium to communicate them. I think it looks great overall, I’m just a straight shooter and tell it how it is.

**Comment by jurialmunkey** [comment]
The issue was already raised. I am very aware of the issue. There is currently no fix.

You adding in your opinion about how it drives you nuts does not add anything or help in anyway to resolve the issue.

**Comment by jurialmunkey** [comment]
I think I have come up with an effective way to address this issue and fallback to the next widget (and so on) if the first in the group is unavailable.

So far seems to be working well in my tests. We'll see if it breaks anything!

**Comment by OfficerKD637** [comment]
> I think I have come up with an effective way to address this issue and fallback to the next widget (and so on) if the first in the group is unavailable.
> 
> So far seems to be working well in my tests. We'll see if it breaks anything!

Hey @jurialmunkey 
Sorry to comment on a closed issue but what kind of magic is this?!! I remember this being an issue in past skins and you had to create the 'fallback paths' feature in Skin Variables to mitigate it. But now you've actually managed to solve the core issue! Woah!!

The only thing I am noticing is that it still misses focus upon Kodi start (the screen stays dim). But once you move the side menu selector and refocus the first side menu icon, it works perfectly! ~~Even multiple skin reloads won’t break this!~~ Sometimes skin reloads can reintroduce the issue, but I’d say it works most of the time!

Oh and the best part is this can be backported to AF1 (which I just tried!)

Can't thank you enough Jurial!! You're truly a wizard!
