### ISSUE TITLE
:bug: Clock on OSD when loading

### ISSUE THREAD

**Issue by seppiola** [jurialmunkey/skin.arctic.fuse.2#65]
### Skin section

Video OSD

### Current Behavior

I happened to notice that the clock doesn't get replaced by the loading circle when opening info on playing video OSD, which instead gets drawn on top of the clock itself for a bad visual effect.
I think this is unwanted since in every other section of the skin the clock usually gets replaced by the loading spinner.

### Expected Behavior

I guess the spinner should replace the clock when needed.
Maybe being drawn next to it?

### Steps To Reproduce

1. Start playing a movie
2. Open the OSD
3. Open Info screen
4. Usually loading takes a second and the spinner should appear on top of the clock

### Screenshots and Additional Info

![19e5bbd8-f8ad-4374-9489-e40194173d82](https://github.com/user-attachments/assets/9f7638a7-fb9b-41d0-8393-fe71d6c6973b)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
It's because in that window it's not the "real" busy spinner and so it doesn't trigger the condition to slide it over. Above commit should fix it for the two fake spinners in the info dialog loader windows.
