### ISSUE TITLE
:bug: TV episode play icon missing with add-on as player

### ISSUE THREAD

**Issue by Ade-AV** [jurialmunkey/skin.arctic.fuse.2#69]
### Skin section

Widgets

### Current Behavior

Hi

If I set tmdb helper to use Umbrella as the player and have a widget with e.g. Next Episodes and then select an Episode to play there is no play icon on the widget just before it plays, if I do the same with Movies then there is a play icon

### Expected Behavior

Play icon to show for Episodes

### Steps To Reproduce

As above

### Screenshots and Additional Info

![image](https://github.com/user-attachments/assets/3b7bfc21-bd56-4bd2-9570-6606713b20c5)

This is the Play icon for Movies (from AF1 - same issue)

Thanks

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Nothing to do with the skin. I cannot help you with third party players for banned addons.

**Comment by Ade-AV** [comment]
OK, thanks
