### ISSUE TITLE
Ratings not showing no spotlight menu to add widget.

### ISSUE THREAD

**Issue by matthius7** [jurialmunkey/skin.arctic.fuse.2#7]
### Skin section

Widgets

### Current Behavior

I've added all info into tmdb for ratings and working on Af not showing on af2. Spotlight isn't anywhere in customize widgets. Overall great start on a fast fast skin. 

### Expected Behavior

Ratings show

### Steps To Reproduce

Add omdb api to tmdb helper and mdb list api

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
Ratings work fine for me.

Home screen does not have spotlight. The home screen is *only* classic widget mode with no info. 

If you want a spotlight or info row based widgets then you should use a Hub window and use the option to set it as the homescreen.

**Comment by matthius7** [comment]
> Ratings work fine for me.
> 
> Home screen does not have spotlight. The home screen is _only_ classic widget mode with no info.
> 
> If you want a spotlight or info row based widgets then you should use a Hub window and use the option to set it as the homescreen.

Thank you very much I'll check it out after work. Very nice swift skin

**Comment by matthius7** [comment]
> Ratings work fine for me.
> 
> Home screen does not have spotlight. The home screen is _only_ classic widget mode with no info.
> 
> If you want a spotlight or info row based widgets then you should use a Hub window and use the option to set it as the homescreen.

Do the ratings only show top right inside a red circle because I got those working. Just not tmdb, RT or anything else.

**Comment by jurialmunkey** [comment]
> Do the ratings only show top right inside a red circle because I got those working. Just not tmdb, RT or anything else.

I still dont know what you mean.

You setup ratings exactly the same as in AF1.

The only different is on the home screen the info panel is not displayed. But anywhere else ratings should display just the same. 

If you already had ratings setup for AF1 then there shouldn't be any need to change anything other than which ratings you want displayed in the skin settings as these will be defaults (kodi, tmdb, awards).
