### ISSUE TITLE
🐛 Signpost cutting off part of text

### ISSUE THREAD

**Issue by Rinicko100** [jurialmunkey/skin.arctic.fuse.2#77]
### Skin section

Widgets

### Current Behavior

Hello Jurial,  I really love this signpost widget style, excellent addition to the view types 

Currently the signpost is cutting off part of the last end of the plot text... if this was for one item, it could be that the plot is longer than usual, but this happens for nearly every item and looks a bit unpleasant 
![Kodi_20241011_044813](https://github.com/user-attachments/assets/f6f9949f-1da1-462d-a705-7dc21c3abece)

Could the space for text be a tiny bit longer or shorter to avoid cutting the text

### Expected Behavior

Text should show normally at the side of the signpost widgets

### Steps To Reproduce

1) Create a widget group
2) Make the style signpost 

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
I cannot support mods. Use the proper font

**Comment by jurialmunkey** [comment]
It works absolutely fine if you haven't modified the skin

![screenshot00704](https://github.com/user-attachments/assets/b2105abb-d388-45f9-8a02-60129c01c372)

**Comment by Rinicko100** [comment]
> It works absolutely fine if you haven't modified the skin
> 
> ![screenshot00704](https://github.com/user-attachments/assets/b2105abb-d388-45f9-8a02-60129c01c372)
> 

Ohh... didn't think about the font. No worries
