### ISSUE TITLE
Skin missing some files

### ISSUE THREAD

**Issue by taiseer999** [jurialmunkey/skin.arctic.fuse.2#94]
### Skin section

Other

### Current Behavior

Updated to 2.09 and skin wont load
![Screenshot 2024-10-13 at 11 07 07 AM](https://github.com/user-attachments/assets/59995680-4973-467f-bdc9-6b81f1f031f9)

### Expected Behavior

to work normally

### Steps To Reproduce

Update

### Screenshots and Additional Info

![Screenshot 2024-10-13 at 11 07 07 AM](https://github.com/user-attachments/assets/052afe8c-a44a-415c-96db-98bcfde4e7fe)

### Checklist

- [X] I have made a separate issue for each bug that I am reporting.
- [X] I have searched the issues and this bug has not been reported.
- [X] I am using the most recent skin version.
- [X] I have confirmed that this bug does not occur in the default skin.

**Comment by jurialmunkey** [comment]
delete addons/packages folder and try redownload/reinstall

this happens when you dont fully download the zip

**Comment by taiseer999** [comment]
I managed to install it manually via downloaded zip file, I noticed that I cannot rename hubs from customize widgets page

**Comment by jurialmunkey** [comment]
> I cannot rename hubs from customize widgets page

I can still rename them fine. I think you've got an old version. If you don't clear packages and try to install from a zip with the same name then Kodi will install the cached version from packages, not your new file.

**Comment by taiseer999** [comment]
I will give it a shot

**Comment by taiseer999** [comment]
All is well thanks
